misc: Update lab-setup guide
cs-pub-ro/operating-systems pull request #104
Opened 2024-10-20 11:48 UTC by Alex-deVis

# Prerequisite Checklist

- [x] Read the [contribution guidelines](https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [x] Tested your changes against relevant architectures and platforms;
- [x] Updated relevant documentation (if needed).

## Description of changes

Add instructions on how to store progress before pulling changes. Recommend that each laboratory should have its own branch to avoid rebase conflicts.
Credits to dr. @edi33416.

2024-10-20 11:57 UTC, teodutu reviewed
Most of our students' changes will be made to the `support/` folders which are `.gitignore`d after adding the infrastructure to generate support code from solutions :))). So `git add support/` will just issue a warning and add nothing without `-f`. You should mention this.

2024-10-20 12:07 UTC, Alex-deVis commented
Will do, but I'd rather store both `support` and `solutions`.

Not storing the progress by default is counterintuitive and having to run `git pull` -> `make skels` every time seems tedious.
On top of this, if the solution changes, you'd have to stash `support` before running `make skels`, which leads to needless complexity for students.

2024-10-20 13:22 UTC, Alex-deVis commented
Depends on: https://github.com/open-education-hub/actions/pull/81.

2024-10-21 15:16 UTC, teodutu requested changes

2024-10-21 15:16 UTC, teodutu commented on misc/lab-setup.md
> +    student@os:~/operating-systems$ git checkout -b lab-Y  # Replace Y with lab number
```suggestion
    student@os:~/operating-systems$ git checkout -b lab-Y main  # Replace Y with lab number
```
Students will most likely be on branch `lab-<Y-1>` when running this command, which will make `lab-Y` have `lab-<Y-1>` as parent instead of `main`

2024-10-21 15:17 UTC, teodutu commented on misc/lab-setup.md
> +If `git status` output differs, follow the [instructions to save your progress](#save-progress-and-prepare-next-lab).
```suggestion
If the `git status` output differs, follow the [instructions to save your progress](#save-progress-and-prepare-next-lab).
```

2024-10-21 15:47 UTC, teodutu approved these changes

2024-10-21 15:50 UTC, merged

2024-10-23 09:33 UTC, edi33416 commented
Thank you @Alex-deVis for the changes