infra/config: Move tasks to the beginning of each lab
cs-pub-ro/operating-systems pull request #112
Opened 2024-10-22 11:29 UTC by teodutu

# Prerequisite Checklist

- [x] Read the [contribution guidelines](https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [x] Tested your changes against relevant architectures and platforms;
- [x] Updated relevant documentation (if needed).

## Description of changes

Move the "Tasks" section at the start of each one-page lab so students aren't tempted to waste time reading the documentation during practical sessions when they should be going straight to the tasks.

2024-10-22 11:34 UTC, teodutu commented
The lab generator script is hardcoded to have tasks at the end [1]. I'll need to amend it to accommodate variable section orders.

[1] https://github.com/cs-pub-ro/operating-systems/blob/13959d127634d81335a2462e6db71b834773b5a7/gen-view.py#L158-L171

2024-10-22 11:42 UTC, Alex-deVis commented
> I'll need to amend it to accommodate variable section orders.

Just go ahead and hardcode tasks first, no reason to make the script 'smarter' right now.
Once we know how much customization is required we'll change the script.

2024-10-22 11:44 UTC, Alex-deVis commented on config.yaml
>    - title: Lab 2 - Library Perspective
While you are doing this, consider adding the long lost guides for this lab. @mariapana would appreciate.

2024-10-26 18:54 UTC, Alex-deVis commented
Just merged #116. Rebase and reorder sections to get this done.

2024-10-27 06:52 UTC, Alex-deVis requested changes

2024-10-27 06:52 UTC, Alex-deVis commented on config.yaml
>        - libcall-syscall.md
Remove these.

2024-10-27 06:52 UTC, Alex-deVis commented on config.yaml
> +      - common-functions.md
This was deleted by mistake when `gen-view.py` was added.
```suggestion
      - guides/static-dynamic.md
      - common-functions.md
```

2024-10-27 09:51 UTC, Alex-deVis approved these changes

2024-10-27 09:52 UTC, merged