chapters/compute: Add checker for lab 8
cs-pub-ro/operating-systems pull request #120
Opened 2024-10-29 18:57 UTC by NickZaharia308

Add checkers for laboratory 8 tasks.

# Prerequisite Checklist

- [ ] Read the [contribution guidelines](https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [ ] Tested your changes against relevant architectures and platforms;
- [ ] Updated relevant documentation (if needed).

## Description of changes

Implemented modifications:
- Q: Reading part from `synchronization.md` is smaller, by moving content from it directly to tasks READMEs. Why?
- A: The reading part should give a perspective of what's next, students should focus on tasks and **learn by doing**.
- Q: First part of the laboratory (Task: Race condition) was moved later on. Why?
- A: Students should first learn the basic concepts of race conditions and synchronization and solve harder tasks later on. Both TLS on demand and atomic assembly were in race condition folder, and there were easier exercises there (including an introduction to race conditions) that were later addresses.
- Q: `race-condition/` folder was divided into smaller ones. Why?
- A: It is easier to follow each concept step by step. Each task introduces a new particularity and should be treated separately.

Unimplemented change (that I'd like to do)
- The laboratory itself is pretty large and contains key concepts about synchronization, race conditions and scheduling. I'd remove (or move to another laboratory or at the end of this laboratory) `Task: Synchronization - Thread-Safe Data Structure` and  `Task: Another Time Slice`.

2024-11-18 23:59 UTC, teodutu requested changes
The new tasks are nicely split from what we had previously. Well done! I made some inline suggestions on how to improve this. First and foremost, fix the checkpatch failures: https://github.com/cs-pub-ro/operating-systems/actions/runs/11787905425/job/32834045148?pr=120

2024-11-18 23:59 UTC, teodutu commented on chapters/compute/synchronization/drills/tasks/atomic-assembly/README.md
> +It's an Assembly equivalent of the code you've already seen many times so far (such as `chapters/compute/synchronization/drills/tasks/race-condition/support/c/race_condition.c`).
Move these files to `atomic-assembly/` and add a checker. Move the function to be made thread-safe in a separate file, and place the checker in a C file that links the aforementioned `.S` file.

2024-11-18 23:59 UTC, teodutu commented on chapters/compute/synchronization/drills/tasks/race-condition/support/c/race_condition_mutex.c
> -	// the running times.
Why remove these `TODOs`? Add a `solution/` folder and use them to generate the `support/` folder from it.

2024-11-18 23:59 UTC, teodutu commented on chapters/compute/threads/guides/sum-array-threads/solution/java/.gitignore
Remove this file because `the global `.gitignore already ignores .class` files`.

2024-11-18 23:59 UTC, teodutu commented on chapters/compute/threads/guides/sum-array-threads/solution/c/add_array_threads_openmp.c
This file mixes tabs and spaces for indentation. Follow the checkpatch failures and fix them.

2024-11-18 23:59 UTC, teodutu commented on chapters/compute/synchronization/drills/tasks/wrap-the-for/solution/src/race_condition_outer_mutex.c
Fix the checkpatch errors in this file.

2024-11-18 23:59 UTC, teodutu commented on chapters/compute/synchronization/drills/tasks/wrap-the-for/README.md
> +# Practice: Wrap the Whole `for` Statements in Critical Sections
```suggestion
# Wrap the Whole `for` Statements in Critical Sections
```

2024-11-18 23:59 UTC, teodutu commented on chapters/compute/synchronization/drills/tasks/wrap-the-for/solution/tests/checker.sh
Run `make build` in this script so students can build and run everything with a single command.

2024-11-19 11:24 UTC, NickZaharia308 commented on chapters/compute/synchronization/drills/tasks/race-condition/support/c/race_condition_mutex.c
> -	// the running times.
I made a separate task with a separate checker in `chapters/compute/synchronization/drills/tasks/wrap-the-for/`, where students have to do that. This way, `race_condition_mutex.c` is just a demo file and they can practice on another file.

2024-11-19 20:14 UTC, NickZaharia308 commented
Two new checkers in `atomic-assembly/` and `race-condition-atomic` have been added.

2024-11-22 18:16 UTC, teodutu requested changes
Things are looking better now. Most of my suggestions now are cosmetic. Fix them, then we can merge this.

2024-11-23 14:53 UTC, NickZaharia308 commented on chapters/compute/synchronization/drills/tasks/apache2-simulator-condition/.gitignore
> +
I use vscode for editing. Shouldn't there be a blank line after the first line?

2024-11-23 15:05 UTC, NickZaharia308 commented on chapters/compute/synchronization/drills/tasks/apache2-simulator-condition/.gitignore
> +
Which editor should I use to see the number of lines correctly?

2024-11-24 13:07 UTC, teodutu commented on chapters/compute/synchronization/drills/tasks/apache2-simulator-condition/.gitignore
> +
> Shouldn't there be a blank line after the first line?
Yes, but you added 2 from what I can see on GitHub.

2024-11-24 17:11 UTC, teodutu approved these changes

2024-11-24 17:16 UTC, teodutu requested changes
Now I see super-linter is complaining about using `\n` in `echo`s [1]. And it's correct. I forgot you need to run `echo -e` for `\n` to be treated as a newline. But it's better to do as it wants and just use `printf`.

[1] https://github.com/cs-pub-ro/operating-systems/actions/runs/11998031715/job/33444336487?pr=120#step:3:629

2024-11-24 19:28 UTC, teodutu approved these changes

2024-11-24 19:29 UTC, merged