Added checkers for lab 9
cs-pub-ro/operating-systems pull request #143
Opened 2024-12-01 19:54 UTC by robertpaulp

# Prerequisite Checklist

- [ ] Read the [contribution guidelines](https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [ ] Tested your changes against relevant architectures and platforms;
- [ ] Updated relevant documentation (if needed).

## Description of changes

2024-12-01 20:38 UTC, Viktor09 approved these changes
Looks good!

2024-12-02 11:54 UTC, teodutu requested changes
Thank you for the scrips. Here's how to improve them.

- Move each checker to `solution/tests/` so that `make skels` places it in `support/tests`. Make sure to run `chmod +x support/tests/checker.sh` in the `skels` Makefile rule. And change the commands in the scripts to refer to their new paths.
- Move the solution code to `solution/src` so that `make skels` places its output in `support/src`.
- And make the original checkers executable.
- Add a CLI snippet where you run the checker script that passes all tests in each task's `README.md`.
- Change your commit message to `chapters/io: Add checker infrastructure for lab 9` followed by a description mentioning the tasks that received checkers.

2024-12-02 11:54 UTC, teodutu commented on chapters/io/file-descriptors/drills/tasks/mmap_cp/checker.sh
> +
```suggestion
Add a `make` command that compiles the source code so students only need to run one command (`./checker.sh`) to rule them all.
```

2024-12-02 11:54 UTC, teodutu commented on chapters/io/file-descriptors/drills/tasks/my-cat/checker.sh
> +exit 0
```suggestion
```

2024-12-02 11:54 UTC, teodutu commented on chapters/io/ipc/drills/tasks/anon-pipes/checker.sh
> +echo -e "\n$input_text\n" > "$SOURCE_DIR/$INPUT_FILE"
Don't make the script interactive. Place the input string in the script. Use 2 strings: a short one for debugging and a longer one (more than 8K to fill the internal buffer) to test correctness.

2024-12-02 11:54 UTC, teodutu commented on chapters/io/file-descriptors/drills/tasks/my-cat/checker.sh
> +test_empty_file() {
This test passes even with the skeleton code. Change the solution and remove the code that `open()`s the input file. Turn it into a `TODO`.

2024-12-02 11:54 UTC, teodutu commented on chapters/io/file-descriptors/drills/tasks/mmap_cp/checker.sh
> +exit 0
```suggestion
```
Remove this from every checker script. It's OK for the scripts to fail

2024-12-02 11:54 UTC, teodutu commented on chapters/io/file-descriptors/drills/tasks/mmap_cp/checker.sh
> +    echo "File copies differ."
Add "test passed" and "test failed" to these messages to clarify when the output is correct and when it isn't.

2024-12-02 15:35 UTC, robertpaulp commented
I've added your suggestions.

2024-12-02 15:40 UTC, teodutu commented
Squash your 2nd commit into the first one. I'm not sure how you got it, but to merge the `main` branch you should do the following:

```
$ git checkout main
$ git fetch upstream  # first set your upstream remote to https://github.com/cs-pub-ro/operating-systems
$ git pull upstream main
$ git checkout -  # - is the previous branch
$ git rebase main  # Fix all conflicts, git add the conflicting files, then git rebase --continue and repeat until all commits are rebased
```
This way you won't get that extra commit that you now need to squash

2024-12-02 15:53 UTC, robertpaulp commented
@teodutu Done.

2024-12-02 16:49 UTC, Viktor09 approved these changes

2024-12-02 18:51 UTC, teodutu requested changes
There's only one merge conflict that you added without solving. See my inline comment and then we can merge this. GJ!

2024-12-03 05:15 UTC, teodutu approved these changes
GG!

2024-12-03 05:15 UTC, merged