Solved the issue 134
cs-pub-ro/operating-systems pull request #149
Opened 2024-12-13 17:47 UTC by teodor994

- Done solving the issue 134 : https://github.com/cs-pub-ro/operating-systems/issues/134
- Added the generate_skels.py infrastructure to generate the skeletons from the solutions
- Added checkers for the tasks which needed one
- Updated the README.md for every task with useful information on how to generate the skels and run the checker
- Added `solution`

2024-12-13 20:19 UTC, teodutu requested changes
Thanks for the contribution. Most of the checkers are working fine. I made a bunch of inline comments. Address them and then below is some more general feedback.

- Update the paths used by the tester scripts and Makefiles from `../` to `../src/`
- Tasks such as `aslr` and `stack-protector` require changing the Makefiles. Add `TODO`s to them. Ideally update `generate_skels.py` to generate support Makefiles from those in `solution/`.
- Fix the CI/CD failures [1]. Spellcheck sometimes outputs false positives caused by words missing from these lists [2]. To fix those, make a PR to add those missing words this repo [2] (use the makefile in [2] to keep the lists sorted).
- Change your commit message to (according to the contributing guidelines [1] ):

```
chapters/data: Add checkers for `memory-security` tasks

<the description of your PR>

Resolves #134

<your signed-off-by line>
```

[1] https://github.com/cs-pub-ro/operating-systems/pull/149/checks
[2] https://github.com/open-education-hub/actions/tree/main/spellcheck/config
[3] https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#commits

2024-12-14 04:06 UTC, teodutu commented
You didn't overwrite your first commit (`git commit --amend`), but created a new onw instead. Now do this to squash them together into a single one:
1. `git rebase -i main`
2. This will open your default editor and you'll see your 2 commits. Replace the first word "pick" with "s" (from "squash") on the second line, then save and exit.
3. A new editor window will open with the 2 commit messages cincatenated, allowing you to modify them. Only keep the latter. And change "Rsolves #134" to "Fixes #134" as I didn't see the issue linked with this PR. Maybe Github doesn't support "Resolves" like its docs say [1]?
4. `git push -f`

[1] https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

2024-12-14 08:38 UTC, Alex-deVis commented
Instead of following the premium tutorial wrote by @teodutu (which he rewrites everytime in a different way), you could follow this guide [1]. The gif shows you a clear example of how to do a `git rebase -i`.

[1] https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec

2024-12-14 12:39 UTC, teodutu reviewed
The checkers are OK. My only questions are why are you running `sudo bash ./run_all_tests.sh` instead of just `./run_all_tests.sh` in `make check`.

2024-12-14 12:39 UTC, teodutu commented on chapters/data/memory-security/drills/tasks/aslr/solution/tests/Makefile
> +	sudo bash ./run_all_tests.sh
Why do you need `sudo`?

2024-12-14 12:39 UTC, teodutu commented on chapters/data/memory-security/drills/tasks/bypassing-stack-protector/solution/tests/Makefile
> +	sudo bash ./run_all_tests.sh
Again: why `sudo bash` and not just `./run_all_tests.sh`?

2024-12-14 12:39 UTC, teodutu commented on chapters/data/memory-security/drills/tasks/stack-protector/solution/tests/Makefile
> +	sudo bash ./run_all_tests.sh
Ditto: you can just run `./run_all_tests.sh`.

2024-12-14 12:48 UTC, teodutu approved these changes
The content is fine. Great job! Fix the linters and then I'll merge this.

2024-12-14 13:39 UTC, teodutu commented
You need to rebase the `main` branch to remove the merge conflicts.

2024-12-14 14:00 UTC, teodutu commented
@Alex-deVis can you figure out what's the conflict here?

2024-12-14 14:17 UTC, Alex-deVis commented
I'll take a look in 30m

2024-12-14 15:20 UTC, merged