infra/linters: Replace spellcheck with misspell
cs-pub-ro/operating-systems pull request #153
Opened 2024-12-14 21:58 UTC by Alex-deVis

# Prerequisite Checklist

- [x] Read the [contribution guidelines](https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [x] Tested your changes against relevant architectures and platforms;
- [x] Updated relevant documentation (if needed).

## Description of changes

Spellcheck is difficult to maintain because it complains about every unknown word, including technical terms, acronyms, and names. Misspell is a more relaxed spellchecker, which only complains about *common* misspellings and lets the user handle new words such as the previous examples.

Additionally, our approach does not scale - the [actions repo](https://github.com/open-education-hub/actions/) has [*64 PRs*](https://github.com/open-education-hub/actions/pulls?q=is%3Apr+is%3Aclosed+spellcheck) that add new words. It is cumbersome to ask a contributor to add common technical terms for each contribution.

2024-12-14 22:13 UTC, teodutu reviewed
Let's give it a shot. It can't be worse than spellcheck. Also add it to the actions repo [1] if it proves useful.

But can you run it locally?

[1] https://github.com/open-education-hub/actions

2024-12-15 10:38 UTC, Alex-deVis commented
@teodutu I rebranded this to add [`Typos`](https://github.com/crate-ci/typos) instead of `misspell`. I tested it locally and got some nice results - check the changed files. The downside is that there is no out-of-the-box docker image to run this locally but we can create our own.

2024-12-15 20:51 UTC, teodutu requested changes
Add a `lint` rule to the Makefile that runs this linter locally.

2024-12-15 20:52 UTC, teodutu commented
Ina addition, you'll have to add exceptions for what's causing `typos` to fail now and fix the other linter errors.

2024-12-29 19:48 UTC, teodutu requested changes

2024-12-29 19:48 UTC, teodutu commented on CPPLINT.cfg
> +filter=-build/include_what_you_use
Why? What did this cause to fail with no reason?

2024-12-29 19:48 UTC, teodutu commented on .vscode/settings.json
Remove this file and add `.vscode/` to the `.gitignore` in the repo's root. It's not the first time that you add it and students have done it more often.

2024-12-29 19:49 UTC, teodutu commented
Also, the super-linter errors do make sense. Fix them: https://github.com/cs-pub-ro/operating-systems/actions/runs/12534993042/job/34956380764?pr=153

2024-12-29 19:49 UTC, Alex-deVis commented on .vscode/settings.json
Stop `.vscode/` shaming, you vim enjoyer.

2024-12-29 19:51 UTC, teodutu commented on .vscode/settings.json
I'm also a `.vscode` fanboy, but I don't `git add .`

2024-12-29 19:51 UTC, Alex-deVis commented on CPPLINT.cfg
> +filter=-build/include_what_you_use
I don't have any example at hand, but there are *a lot* of spurious warnings regarding missing imports even though the files compile. It would be easy anyway to figure out if you have missing imports.

2024-12-29 20:13 UTC, teodutu commented on CPPLINT.cfg
> +filter=-build/include_what_you_use
The leave it be. Those warnings aren't spurious. If we need to ignore them, we can just do so individually for each file.

2024-12-30 09:08 UTC, Alex-deVis commented
The `checkpatch` action will be fixed once https://github.com/open-education-hub/actions/pull/100 is merged. The errors in `superlinter` are false positives.

2024-12-30 13:36 UTC, teodutu approved these changes
That one super-linter error is acutally bullshit. You can ignore it inline AFAIK, right?

2024-12-30 16:15 UTC, Alex-deVis commented
> That one super-linter error is acutally bullshit. You can ignore it inline AFAIK, right?

No, you need to define a `CPPLINT.cfg` in that directory, which will overwrite the `CPPLINT.cfg` in the repo root. 

The `[build/include_what_you_use]` error appears for a lot of our source files and always complains about not including `string.h` even though the sources compile. Since we are testing changes (mostly in production), missing imports will not be a problem, so I would rather remove this rule than having PRs falling over this.

For concrete examples, checkout https://github.com/cs-pub-ro/operating-systems/pull/150 and remove the `[build/include_what_you_use]` line from the root `CPPLINT.cfg`.

What do you suggest, we ignore it globally or tackle it as we go?

2024-12-30 16:23 UTC, teodutu commented
Ok now removing it in #150 makes sense. It seems this check spits false positive errors when encountering the string `string` :)))).

2025-01-02 17:19 UTC, merged