misc: Add grading rules from ocw
cs-pub-ro/operating-systems pull request #2
Opened 2023-10-11 20:27 UTC by Alex-deVis

Add initial version of the rules for the Operating Systems course inspired by the previous version on OCW.
This version contains TODOs and TBAs.

2023-10-11 20:43 UTC, teodutu requested changes
I made a partial review

2023-10-11 20:43 UTC, teodutu commented on content/misc/rules-and-grading.md
> +
```suggestion

```

2023-10-11 20:43 UTC, teodutu commented on content/misc/rules-and-grading.md
> +  - It will last for **20 minutes**.
```suggestion

  - It will last for **20 minutes**.
```

2023-10-11 20:43 UTC, teodutu commented on content/misc/rules-and-grading.md
> +1. Concepts Understanding
```suggestion
1. Understanding Concepts
```

2023-10-11 20:43 UTC, teodutu commented on content/misc/rules-and-grading.md
> +  - You will receive **11 True/False questions** that require explanations.
```suggestion
  - You will receive **11 True/False questions** that require explanations.
  - You will receive 0 points if you choose the right answer, but the explanation is wrong.
```

2023-10-11 20:43 UTC, teodutu commented on content/misc/rules-and-grading.md
> +  However, internet access will not be allowed.
Isn't it? Asking questions isn't allowed, but using the internet in a read-only manner is.

2023-10-11 20:43 UTC, teodutu commented on content/misc/rules-and-grading.md
> +In total, there are 5 assignments, 2 of which are bonus.
```suggestion
There are 3 assignments, followed by 2 bonus ones.
```
Such that we never state the obvious: that there are 5 assignments.

2023-10-11 20:43 UTC, teodutu commented on content/misc/rules-and-grading.md
> +- 2 points for completing the **bonus exercises** of the laboratory
```suggestion
- 2 points for **bonus activity** during the laboratory.
They are awarded by the TA according to their own criteria: interesting questions, good answers, solving bonus tasks, helping other students, etc.
```

2023-10-11 20:43 UTC, teodutu commented on content/misc/rules-and-grading.md
> +If you missed a lab or did not receive the maximum score on other labs, the lab bonuses will assist you in improving your final grade.
```suggestion
If you miss a lab or do not receive the maximum score on other labs, the lab bonuses will assist you in improving your final grade.
```

2023-10-11 20:43 UTC, teodutu commented on content/misc/rules-and-grading.md
> +**Collaboration during lab sessions is encouraged.**
```suggestion
**Collaboration during lab sessions is strongly encouraged.**
```

2023-10-12 06:22 UTC, elena19m reviewed
I've added suggestions for the TODOs in the course quizzes and pins sections.

2023-10-12 06:22 UTC, elena19m commented on content/misc/rules-and-grading.md
> +    - Series CD: **TBA**
```suggestion
    - Series CA: 07.11.2023
    - Series CB: 08.11.2023
    - Series CC: 07.11.2023
    - Series CD: 07.11.2023
```

2023-10-12 06:22 UTC, elena19m commented on content/misc/rules-and-grading.md
> +    - Series CD: **TBA**
```suggestion
    - Series CA: 05.12.2023
    - Series CB: 06.12.2023
    - Series CC: 05.12.2023
    - Series CD: 05.12.2023
```

2023-10-12 06:22 UTC, elena19m commented on content/misc/rules-and-grading.md
> +    - Series CD: **TBA**
```suggestion
    - Series CA: 09.01.2024
    - Series CB: 10.01.2024
    - Series CC: 09.01.2024
    - Series CD: 09.01.2024
```

2023-10-12 06:22 UTC, elena19m commented on content/misc/rules-and-grading.md
> +The quizzes will be held on the Moodle platform during the class and will last for **5 minutes**.
```suggestion
The quizzes  are closed-book, will be held on the Moodle platform during the class and will last for **5 minutes**.
```

2023-10-12 06:22 UTC, elena19m commented on content/misc/rules-and-grading.md
> +- **TBA** distinctions for community involvement (pull requests, forum discussions, etc.).
```suggestion
- 8 distinctions for involvement in course activities.
- 20 distinctions for involvement in laboratory activities.
- 5 distinctions for interesting implementations of assignments.
- 8 distinctions for exam results.
- 10 distinctions for community involvement (pull requests, forum discussions, etc.).
```

2023-10-12 08:28 UTC, fabianpatras commented on content/misc/rules-and-grading.md
> +During the semester, students will be rewarded with distinctions.
```suggestion
After the semester, students will be rewarded with distinctions based on their involvement in certain activities.
```

2023-10-12 09:44 UTC, fabianpatras commented
> Published at http://open-education-hub.github.io/operating-systems/2/

This gives 404.

2023-10-15 14:54 UTC, razvand commented
@Alex-deVis, I'll check this later today and be back with feedback, so we can then merge it.

2023-10-16 02:11 UTC, razvand requested changes
See my comments.

2023-10-16 02:11 UTC, razvand commented on content/misc/rules-and-grading.md
> +The concept of copied assignments includes, but is not limited to, situations such as:
```suggestion
The concept of plagiarized assignments includes, but is not limited to, situations such as:
```

2023-10-16 02:11 UTC, razvand commented on content/misc/rules-and-grading.md
> +In the event that two assignments are deemed copied, both the source and destination will receive identical penalties, without discussions regarding who copied from whom and whose fault it is.
```suggestion
In the event that two assignments are deemed plagiarized, both the source and destination will receive identical penalties, without discussions regarding who copied from whom and whose fault it is.
```

2023-10-16 02:11 UTC, razvand commented on content/misc/rules-and-grading.md
> +We emphasize that our goal is not and will not be to penalize for copying.
```suggestion
We emphasize that our goal is not and will not be to penalize for plagiarism.
```

2023-10-16 02:11 UTC, razvand commented on content/misc/rules-and-grading.md
> +We view copying as a dishonest act that will be punished if it occurs.
```suggestion
We view plagiarism as a dishonest act that will be punished if it occurs.
```

2023-10-16 02:11 UTC, razvand commented on content/misc/rules-and-grading.md
> +The laboratory sessions are conducted in a physical format in the rooms assigned according to the schedule.
```suggestion
Laboratory sessions take part in person in the lab rooms assigned according to the schedule.
```

2023-10-16 02:11 UTC, razvand commented on content/misc/rules-and-grading.md
> +The groups are divided in half (into two equally-sized subgroups or with a maximum difference of one student).
```suggestion
Student groups are divided in half (into two equally-sized subgroups or with a maximum difference of one student).
```

2023-10-16 02:11 UTC, razvand commented on content/misc/rules-and-grading.md
> +**The maximum number of students in a laboratory is 16.**
```suggestion
**The maximum number of students in a lab slot is 16.**
```

2023-10-16 02:11 UTC, razvand commented on content/misc/rules-and-grading.md
> +In the resit/improvement session in the fall and in the special summer session (**only for 4th-year students**), only the exam can be retaken, which consists of the two components: the open-book inte
```suggestion
During the autumn exam and the special summer session (**only for 4th-year students**), only the exam can be retaken.
The exam consists of the two components: the open-book interview and the written synthesis part.
```

2023-10-16 02:11 UTC, razvand commented on content/misc/rules-and-grading.md
> +The coursework assignments are not retaken.
```suggestion
```

2023-10-16 02:11 UTC, razvand commented on content/misc/rules-and-grading.md
> +Assignments cannot be submitted during the vacation period.
```suggestion
Assignments cannot be resubmitted.
```

2023-10-16 02:11 UTC, razvand commented on content/misc/rules-and-grading.md
> +You can participate in the exam to improve the grade obtained in the summer session.
```suggestion
You can reatek exam to improve the grade obtained in the first exam session.
```

2023-10-16 02:11 UTC, razvand commented on content/misc/rules-and-grading.md
> +In the case of participation for grade improvement, the grade obtained in this manner will replace the previously obtained grade from the summer session.
```suggestion
In the case of participation for grade improvement, the grade obtained in this manner will replace the grade in the first exam session.
```

2023-10-16 02:11 UTC, razvand commented on content/misc/rules-and-grading.md
> +Grades will be recorded in the official register, following the course's register.
```suggestion
```

2023-10-16 02:11 UTC, razvand commented on content/misc/rules-and-grading.md
> +- If you wish, you can retain the grades for the course's lab components (laboratory and/or assignments).
```suggestion
- If you wish, you can retain the grades for the course's practical components (laboratory and/or assignments).
```

2023-10-16 02:11 UTC, razvand commented on content/misc/rules-and-grading.md
> +You **cannot** retain the grades for the course components (coursework and the final exam).
```suggestion
You **cannot** retain the grades for lecture components (lecture tests and exam).
```

2023-10-16 02:11 UTC, razvand commented on content/misc/rules-and-grading.md
> +- The rules and grading system for students retaking the course are the same as for students in the current year (course quizzes + exam, homework assignments, etc.).
```suggestion
- The rules and grading system for students retaking the course are the same as for students in the current year (lecture tests + exam, assignments, etc.).
```

2023-10-16 02:11 UTC, razvand commented on content/misc/rules-and-grading.md
> +Like other students, the attendance list becomes fixed starting from the third week.
```suggestion
  Like other students, the attendance list becomes fixed starting from the third week.
```

2023-10-16 02:11 UTC, razvand commented on content/misc/rules-and-grading.md
> +- Students retaking the course can participate in any lecture, course test, and final exam date, regardless of the series to which they belonged.
```suggestion
- Students retaking the course can participate in any lecture, lecture test, and exam, regardless of the series to which they belonged.
```

2023-10-16 05:40 UTC, Alex-deVis commented on content/misc/rules-and-grading.md
> +
This is already stated below, under #exam:

> **Passing the course requires obtaining a minimum of 2 out of 4 points (i.e., 50%) of the exam score.**

2023-10-16 05:40 UTC, Alex-deVis commented on content/misc/rules-and-grading.md
> +    - The maximum score is 11 (out of 10), with 1 point as a bonus.
I checked and the recommended [markdown indentation for sublists is **4 spaces**](https://docs.newrelic.com/docs/style-guide/structure/styleguide-markup-indentation/#four-space).

2023-10-16 05:48 UTC, Alex-deVis commented
@razvand I applied most of your comments except for the ones I replied to. 
I am waiting for your feedback on the last two TODO items:
- What is the minimum grade to skip the exam (if this idea materializes)
- What is the score for each assignment?

2023-10-16 05:49 UTC, Alex-deVis commented on content/misc/rules-and-grading.md
> +  However, internet access will not be allowed.
@teodutu looks like the internet is a thing of the past.

2023-10-17 23:47 UTC, razvand approved these changes
All good.

2023-10-17 23:48 UTC, merged