misc: Add resources from OCW
cs-pub-ro/operating-systems pull request #21
Opened 2023-10-30 16:44 UTC by StefanJum

Add resources for the Operating Systems course.

2023-11-01 09:32 UTC, Alex-deVis commented on content/misc/resources.md
> +You can also find the course planning [here](https://docs.google.com/spreadsheets/d/11-csi2HtJP1HMT63NWy0Y9WpHxyVpxN-hqw7Y45ZH5c/edit?usp=sharing).
```suggestion
You can also find the course planning [here](https://docs.google.com/spreadsheets/d/1HVCP7ybjrtrtN5MMQYbSnvHoals5IbagtY1SaG9K3FE/edit?usp=sharing).
```

2023-11-01 09:32 UTC, Alex-deVis commented on content/misc/resources.md
> +After you install `UTM` and download and unzip the archive, you can import it using the `Open existing VM` option in `UTM`.
You can also reference the instructions from [macos-vm/README.md](https://github.com/cs-pub-ro/operating-systems/blob/main/util/macos-vm/README.md).

2023-11-01 09:39 UTC, teodutu requested changes
Let's add the planning as well as in my inline suggestion.

2023-11-01 09:39 UTC, teodutu commented on content/misc/resources.md
> +
```suggestion
- [OS Activities Planning](https://docs.google.com/spreadsheets/d/1HVCP7ybjrtrtN5MMQYbSnvHoals5IbagtY1SaG9K3FE/edit)

```
So students know what lab is next.

2023-11-04 12:13 UTC, Alex-deVis approved these changes
Looks good.

2023-11-04 12:14 UTC, merged