`common`: Add script to compute final project grade
cs-pub-ro/operating-systems pull request #3
Opened 2023-10-16 16:07 UTC by razvand

The `grade.sh` script computes the final project grade, from two components: checker output and style checking.

Currently, checker output provides a maximum of 90 points and style checking an output of maximum 10 points, for a total maximum of 100 points.

Script it to be symlinked to the `tests/` directory of each project. It invokes the `check` rule and the `lint` rule in the tests Makefile, then proceeds to compute the summary result.

2023-10-16 21:43 UTC, Dave080302 commented on content/common/projects/grade.sh
> +    compiler_warn=$(< checker.out grep -v 'unused parameter' | grep -v 'unused variable' | \
Should we consider adding checks to this? Like the "alignment should match open paranthesis check", I personally think that writing a function like
memcpy(very_long_data_sequence, I_should_progress_to_the_next_line
                                                         3rdparameter)
would be a major coding style issue aswell, and in checkpatch that is not considered either a warning or an error, it's marked as a "check"

2023-10-17 08:26 UTC, CatalinACS reviewed
I would also like to point out the fact that there is no checking in script for using _**goto**_ instruction, it should be marked as an error or warning.
Yes, I do agree that it's very unlikely to find a C source code made by students using that instruction, but from my point of view it should worth considering that edge case.
Besides that, the script looks all right to me.

2023-10-17 09:53 UTC, Dave080302 commented
> I would also like to point out the fact that there is no checking in script for using _**goto**_ instruction, it should be marked as an error or warning. Yes, I do agree that it's very unlikely to find a C source code made by students using that instruction, but from my point of view it should worth considering that edge case. Besides that, the script looks all right to me.

I don't think goto's are necesarrily bad, it's used everywhere in C development when we want to free the memory we allocated in the same function, most consider their absence to be a coding style error.

2023-10-17 21:17 UTC, razvand commented on content/common/projects/grade.sh
> +    compiler_warn=$(< checker.out grep -v 'unused parameter' | grep -v 'unused variable' | \
Yes, of course. But this would be the role of a linter as part of each assignment. We use `checkpatch.pl` and `cpplint`; we may use others, of course. If you can locate a linter that does that, we will add it to the assignment style checking.

2023-10-17 21:18 UTC, razvand commented
> > I would also like to point out the fact that there is no checking in script for using _**goto**_ instruction, it should be marked as an error or warning. Yes, I do agree that it's very unlikely to find a C source code made by students using that instruction, but from my point of view it should worth considering that edge case. Besides that, the script looks all right to me.
> 
> I don't think goto's are necesarrily bad, it's used everywhere in C development when we want to free the memory we allocated in the same function, most consider their absence to be a coding style error.

I agree with @Dave080302 . There are cases when `goto` makes sense.

That being said, if there is a linter or static analyzer that we can integrate that marks the bad `goto` statements, let's use it.

2023-10-18 07:31 UTC, Alex-deVis requested changes
I tested it locally and it works fine after fixing the path for the linter output.

When you create the symlinks to this script from each assignment folder, please make sure that `make lint` calls `checkpatch.pl` correctly.
In the case of `memory-allocator`, it lacked the `--no-tree` flag.

2023-10-18 07:31 UTC, Alex-deVis commented on content/common/projects/grade.sh
> +    checkpatch_warn=$(< checker.out grep 'total: [0-9]* errors' | grep -o '[0-9]* warnings,' | \
```suggestion
    cpplint=$(< linter.out grep "Total errors found:" | rev | cut -d ' ' -f 1 | rev)
    checkpatch_err=$(< linter.out grep 'total: [0-9]* errors' | grep -o '[0-9]* errors,' | \
        cut -d ' ' -f 1 | paste -s -d '+' | bc)
    checkpatch_warn=$(< linter.out grep 'total: [0-9]* errors' | grep -o '[0-9]* warnings,' | \
```
The output for `cpplint` and `checkpatch` is in `linter.out`.

2023-10-18 07:31 UTC, Alex-deVis commented on content/common/projects/grade.sh
> +        < checker.out grep 'total: 0 errors' | grep '[1-9][0-9]* warnings'
```suggestion
        < linter.out grep "Total errors found: [1-9]"
        < linter.out grep 'total: [1-9]* errors'
        < linter.out grep 'total: 0 errors' | grep '[1-9][0-9]* warnings'
```

2023-10-20 08:19 UTC, razvand commented on content/common/projects/grade.sh
> +    checkpatch_warn=$(< checker.out grep 'total: [0-9]* errors' | grep -o '[0-9]* warnings,' | \
@Alex-deVis , checkpatch configuration is only part of Docker. The script is supposed to run correctly, currently, only on Docker. We will update it to work correctly locally sometime later.

2023-10-20 09:27 UTC, Alex-deVis commented on content/common/projects/grade.sh
> +    checkpatch_warn=$(< checker.out grep 'total: [0-9]* errors' | grep -o '[0-9]* warnings,' | \
I do not understand what this has to do with Docker, but I see you changed it as I suggested so it's fine.

2023-10-20 10:28 UTC, razvand commented on content/common/projects/grade.sh
> +    checkpatch_warn=$(< checker.out grep 'total: [0-9]* errors' | grep -o '[0-9]* warnings,' | \
@Alex-deVis , I was referring this comment:

"""
 In the case of memory-allocator, it lacked the --no-tree flag.
 ```

2023-10-20 10:31 UTC, Alex-deVis approved these changes
Looks good

2023-10-20 10:32 UTC, merged