content/assignments: Add "Lambda Function Loader" hackathon
cs-pub-ro/operating-systems pull request #32
Opened 2023-11-28 12:18 UTC by teodutu

# Prerequisite Checklist

- [x] Read the [contribution guidelines](https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [x] Tested your changes against relevant architectures and platforms;
- [x] Updated relevant documentation (if needed).

## Description of changes

- Add the hackathon description
- Add grading and submission instructions
- Update `config.yaml` to render the new changes

2023-11-28 12:47 UTC, Alex-deVis approved these changes

2023-11-28 12:47 UTC, Alex-deVis commented on content/assignments/lambda-function-loader/README.md
> +Grading will consider results obtained solely from the OS virtual machine environment.
```suggestion
Grading will consider results obtained solely in the OS virtual machine environment.
```

2023-11-28 12:47 UTC, Alex-deVis commented on content/assignments/lambda-function-loader/README.md
> +The project architecture embraces a client-server model, where the server is responsible for receiving and fulfilling requests to execute functions sourced from specific dynamic libraries present wit
```suggestion
The project architecture embraces a [client-server model](https://cs-pub-ro.github.io/operating-systems/Lab/IO/client-server-model), where the server is responsible for receiving and fulfilling requests to execute functions sourced from specific dynamic libraries present within the system.
```

2023-11-28 12:47 UTC, Alex-deVis commented on content/assignments/lambda-function-loader/README.md
> +**Tip:**
```suggestion
Operations conducted after execution, regardless of the library's presence in memory.

**Tip:**
```

2023-11-28 15:13 UTC, elena19m commented on content/misc/rules-and-grading.md
> +1. TODO: prizes
```suggestion
1. First place: 900 RON gift card.
2. Second place: 800 RON gift card.
3. Third place: 700 RON gift card.
```

2023-11-28 15:13 UTC, elena19m commented on content/misc/rules-and-grading.md
> +Winning teams will be announced by TODO-date.
```suggestion
Winning teams will be announced by December 20, 2023.
```

2023-11-28 20:09 UTC, fabianpatras approved these changes

2023-11-29 09:20 UTC, elena19m approved these changes

2023-11-29 12:16 UTC, elena19m requested changes

2023-11-29 12:16 UTC, elena19m commented on content/assignments/lambda-function-loader/src/server.c
> +		return -1;
These two lines should be deleted.  `sscanf` returns the number of items (strings) assigned. If `ret == 1`, we should run the default function (`run`) from the `name` library; if `ret == 2`, we should run the `func` function from the `name` library etc.

2023-12-01 07:21 UTC, teodutu commented
Done @elena19m. I also updated the solution in cs-pub-ro/operating-systems-internal#13 accordingly.

2023-12-05 09:53 UTC, merged