content/assignments: Add "Lambda Function Loader" checker
cs-pub-ro/operating-systems pull request #38
Opened 2023-12-09 11:57 UTC by fabianpatras

Add `tests/` directory.
In oreder to run the checker, `cd` into `tests` and run `make check`.

# Prerequisite Checklist

- [ ] Read the [contribution guidelines](https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [ ] Tested your changes against relevant architectures and platforms;
- [ ] Updated relevant documentation (if needed).

## Description of changes

This *draft* PR adds `tests` to the Lambda Loader assignment.

TODO:
- update assignment's `README.md` file to reflect the new rules on how to run the checker.

2023-12-09 22:43 UTC, teodutu requested changes
I just made a brief suggestion without having tested the checker yet

2023-12-09 22:43 UTC, teodutu commented on content/assignments/lambda-function-loader/tests/Makefile
> +.PHONY: build
```suggestion
.PHONY: build check clean
```

2023-12-09 22:43 UTC, teodutu commented on content/assignments/lambda-function-loader/tests/Makefile
> +.PHONY: check
```suggestion
```

2023-12-09 22:43 UTC, teodutu commented on content/assignments/lambda-function-loader/tests/Makefile
> +.PHONY: clean
```suggestion
```

2023-12-15 18:51 UTC, elena19m requested changes

2023-12-15 18:51 UTC, elena19m commented on content/assignments/lambda-function-loader/README.md
> +# Note: When <function> is not provided, the server will try to execute the `run` function.
```suggestion
# Note: When <function> is not provided, the server must execute the `run` function.
```

2023-12-15 18:51 UTC, elena19m commented on content/assignments/lambda-function-loader/README.md
>  # Execute the "function" function from libbasic.so
```suggestion
# Execute the "function" function from libbasic.so. The function does not exist, so an error is printed instead.
```

2023-12-15 18:51 UTC, elena19m commented on content/assignments/lambda-function-loader/README.md
> +# Execute the "cat" function from libbasic.so with the argumentbeing the full path of file "Makefile"
```suggestion
# Execute the "cat" function from libbasic.so with the argument being the full path of file "Makefile"
```

2023-12-15 18:51 UTC, elena19m commented on content/assignments/lambda-function-loader/README.md
> +- it then kills the `server`
```suggestion
- it automatically builds the source files then it starts the `server`.
- it runs all the tests without restarting the `server`.
- it then kills the `server`.
```

2023-12-15 19:30 UTC, teodutu requested changes
- The checkpatch errors are BS. Ignore them.
- I made inline suggestions for fixing the super-linter errors coming from `README.md`. Others such as these [1, 2, 3] and others like them can be fixed. The errors pretty much tell you how to fix them.
- Fuck the spellcheck errors. Its wordlist is way too short.

[1] https://github.com/cs-pub-ro/operating-systems/actions/runs/7226047704/job/19690782887?pr=38#step:3:701
[2] https://github.com/cs-pub-ro/operating-systems/actions/runs/7226047704/job/19690782887?pr=38#step:3:732
[3] https://github.com/cs-pub-ro/operating-systems/actions/runs/7226047704/job/19690782887?pr=38#step:3:1017

2023-12-15 19:30 UTC, teodutu commented on content/assignments/lambda-function-loader/tests/basic.c
> +
```suggestion
```

2023-12-15 19:30 UTC, teodutu commented on content/assignments/lambda-function-loader/README.md
> +# Execute the "function" function from libbasic.so. The function does not exist, so an error is printed.
```suggestion
# Execute the "function" function from libbasic.so.
# The function does not exist, so an error is printed.
```

2023-12-15 19:30 UTC, teodutu commented on content/assignments/lambda-function-loader/README.md
> +student@os:../lambda-function-loader/src$ make
```suggestion
student@os:.../lambda-function-loader/src$ make
```
`..` tends to be confused with the previous directory. `...` are generally used to symbolise a longer path. Do this for all paths.

2023-12-15 19:30 UTC, teodutu commented on content/assignments/lambda-function-loader/README.md
> +For debugging purposes, you can instruct the checker to restart the server before each test. Please see below.
```suggestion
For debugging purposes, you can instruct the checker to restart the server before each test.
Please see below.
```

2023-12-15 19:30 UTC, teodutu commented on content/assignments/lambda-function-loader/README.md
> +- it automatically builds the source files then it starts the `server`.
```suggestion

- it automatically builds the source files then it starts the `server`.
```

2023-12-15 21:54 UTC, elena19m approved these changes

2023-12-16 05:41 UTC, teodutu approved these changes
:+1:

2023-12-16 06:30 UTC, merged