io/lab: Fix strtok_r usage in Mini-shell
cs-pub-ro/operating-systems pull request #42
Opened 2023-12-11 22:00 UTC by teodorobert

# Prerequisite Checklist

- [x] Read the [contribution guidelines](https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [x] Tested your changes against relevant architectures and platforms;
- [x] Updated relevant documentation (if needed).

## Description of changes

Currently the code fails to compile because `strtok_r` is not provided the `saveptr` argument.

This pull request fixes this and synchronizes the changes to the solution. It also removes the `TODO:` marker from one of the comments as there is nothing to do.

2023-12-12 13:36 UTC, teodutu requested changes
Looks legit. Thanks. Please remove the whitespace that I mentioned to pacify superlinter [1]. Do this within the same commit by using

```
git add <file_name>
git commit --amend --no-edit
git push -f
```

[1] https://github.com/cs-pub-ro/operating-systems/actions/runs/7173879807/job/19552630841?pr=42#step:3:621

2023-12-12 13:36 UTC, teodutu commented on content/chapters/io/lab/solution/mini-shell/mini_shell.c
>  	char *token;
```suggestion
	char *token;
```

2023-12-14 04:57 UTC, teodorobert commented
Thanks. It should be good now.

2023-12-14 07:36 UTC, teodutu approved these changes
:ok_hand:

2023-12-14 07:36 UTC, merged