Added arm directory to exercise 3
cs-pub-ro/operating-systems pull request #5
Opened 2023-10-17 08:44 UTC by ummthespruce

2023-10-18 21:15 UTC, gabrielmocanu requested changes
Hi @ummthespruce 
Thanks for this PR, I left a review for what needs to be changed.
It would be great to make the changes and the request my review again.

2023-10-18 21:15 UTC, gabrielmocanu commented on content/chapters/software-stack/lab/support/basic-syscall/arm/Makefile
> +LDFLAGS = -nostdlib -no-pie -Wl,--entry=main -Wl,--build-id=none
```suggestion
```

2023-10-18 21:15 UTC, gabrielmocanu commented on content/chapters/software-stack/lab/support/basic-syscall/arm/hello.s
> +    /*
```suggestion
    /*
```

2023-10-18 21:15 UTC, gabrielmocanu commented on content/chapters/software-stack/lab/support/basic-syscall/arm/hello.s
> +    svc #0
```suggestion
```
You can remove these lines since they are explained above.

2023-10-18 21:15 UTC, gabrielmocanu commented on content/chapters/software-stack/lab/support/basic-syscall/arm/hello.s
> +    /* ldr <register>, =<value>, moves any value but slower*/
```suggestion
    /* ldr <register>, =<value>,loads a value, usually an address */
```

2023-10-18 21:15 UTC, gabrielmocanu commented on content/chapters/software-stack/lab/support/basic-syscall/arm/hello.s
> +    /* svc #<value>, syscall*/
```suggestion
    /* svc #<value>, syscall (use value 0 for syscall) */
```

2023-10-18 21:18 UTC, gabrielmocanu commented
Also, it would be great to change the commit message, to something like this:
software-stack/lab: Add arm implementation for basic-syscall exercise

Add arm skeleton from basic-syscall exercise

Signed-off-by: YOUR_NAME <YOUR_EMAIL>

2023-10-21 17:54 UTC, Alex-deVis commented
Hi, @ummthespruce, this PR addresses issue #4. Add this to the PR description using a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Closes #4".

You should squash all of your commits, sign the resulting commit, and force-push it. This should get rid of the checkpatch errors.

2023-10-24 08:01 UTC, gabrielmocanu commented
@ummthespruce  Please address what @Alex-deVis  said.
If you need any help, please let us know.

2023-10-31 08:39 UTC, gabrielmocanu commented
@ummthespruce 
First configure your name and email.
```
git config --global user.name "Your Name"
git config --global user.email "your email"
```

After this, you can follow [this](https://www.baeldung.com/ops/git-squash-commits) tutorial in order to squash your commits into a single commit. In the final phase, you should have a single commit merged into the main branch.

After you rebase your branch and apply a single commit make sure to put the right commit message as I mentioned above, this should work with:
```
git commit --amend -s
```

- -s flag will add your signature
- --amend will open your editor with the current commit message to be able to edit it

2023-10-31 09:06 UTC, closed without merging