Initial commit for data restructuring.
cs-pub-ro/operating-systems pull request #71
Opened 2024-03-21 13:51 UTC by Grizzlly

# Prerequisite Checklist

- [x] Read the [contribution guidelines](https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [ ] Tested your changes against relevant architectures and platforms;
- [ ] Updated relevant documentation (if needed).

## Description of changes

2024-03-21 23:27 UTC, teodutu requested changes
I made an initial pass highlighting the main things to do. Apply them to the other subchapter as well in a similar fashion. In addition, change your commit message following the requirements in the contributing guidelines [1]

[1] https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests

2024-03-22 07:49 UTC, teodutu commented
In addition, there are a few false positives flagged by the Spellcheck action [1]. Add them to these wordlists [2], according to the topic to which they belong. After updating the wordlists, make sure you run `sort -u -o <wordlist_name.txt> <wordlist_name.txt>` to keep it sorted.

[1] https://github.com/cs-pub-ro/operating-systems/actions/runs/8376098698/job/22934978200?pr=71
[2] https://github.com/open-education-hub/actions/tree/main/spellcheck/config

2024-03-24 17:08 UTC, Grizzlly commented
> I made an initial pass highlighting the main things to do. Apply them to the other subchapter as well in a similar fashion. In addition, change your commit message following the requirements in the contributing guidelines [1]
> 
> [1] https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests

Is `chapters/data` a good prefix? Or should it be more expressive like `chapters/data/drills`?

2024-03-24 18:13 UTC, Grizzlly commented
@teodutu I have a problem when I build the site with the slides via `make`. This happens in the software stack too. I get a bunch of errors like this:

![image](https://github.com/cs-pub-ro/operating-systems/assets/19261573/911913ca-742d-4ebc-bb5e-7e5c6e4b0e3b)

Any way to fix it?

2024-03-24 21:26 UTC, teodutu commented
> > I made an initial pass highlighting the main things to do. Apply them to the other subchapter as well in a similar fashion. In addition, change your commit message following the requirements in the contributing guidelines [1]
> > [1] https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests
> 
> Is `chapters/data` a good prefix? Or should it be more expressive like `chapters/data/drills`?

`chapters/data` is good since you're going to add reading, slides, guides, media, drills etc.

2024-03-24 22:01 UTC, teodutu commented
> @teodutu I have a problem when I build the site with the slides via `make`. This happens in the software stack too. I get a bunch of errors like this:
> 
> ![image](https://private-user-images.githubusercontent.com/19261573/316330761-911913ca-742d-4ebc-bb5e-7e5c6e4b0e3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMTU4MDAsIm5iZiI6MTcxMTMxNTUwMCwicGF0aCI6Ii8xOTI2MTU3My8zMTYzMzA3NjEtOTExOTEzY2EtNzQyZC00ZWJjLWJiNWUtN2U1YzZlNGIwZTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDIxMjUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwNDU3ZDA4MzVjOTVlMGQyNTQxOTNhMmZjZDU2NmRlMzgxMDcyZTUxODIxZThkMzg1Mzk1NGVmMGVjYzU3NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rxq08ofia_Eqqt01T1gBTcxPrl_tZYL8KXAFpgDQsXs)
> 
> Any way to fix it?

The thing is that now because the paths to the media files have been moved relative to `slides.mdpp` (they used to be at the same level, but now they are one level lower - in the directories that correspond to each subchapter), `make html` doesn't work out of the box.

However, the builder used when you run `make build` in the root of the repo copies each subchapter's media files so the rendered website has correct paths. Therefore, you can use `make build` to view the slides.

2024-04-02 23:12 UTC, Grizzlly commented on chapters/data/investigate-memory/reading/investigate-memory.md
> +## Memory Leaks
In what sense?

2024-04-02 23:14 UTC, Grizzlly commented on chapters/data/investigate-memory/reading/investigate-memory.md
> +student@os:~/.../lab/support/memory-leak$ make
Shouldn't it be `drills/...` then?

2024-04-04 09:40 UTC, teodutu commented on chapters/data/arena/reading/arena.md
Yup. Each subsection in the Arena needs to be a separate task inside the `drills/tasks/` folder. It should be structured just like any other task:

```
task-name/
|-- README.md
|-- support/
`-- solution/
```
Keep the name of the tasks as it is in README.md, but call it `BONUS - Task Name` in `config.yaml` for now, so we know which was which.

2024-04-04 09:51 UTC, teodutu commented on chapters/data/investigate-memory/reading/investigate-memory.md
> +## Memory Leaks
Move this section to `guides/memory-leaks/`. This folder should have the following structure:

```
memory-leaks/
|-- README.md
`-- support/
```

Guides are types of content that students are supposed to follow in a directed manner. This direction may come either from the teacher or the detailed descriptions in the `README.md` file. You can read about guides here: https://open-education-hub.github.io/methodology/Developing%20and%20Organizing%20Content/Guides/read

2024-04-04 09:52 UTC, teodutu commented on chapters/data/investigate-memory/reading/investigate-memory.md
> +student@os:~/.../lab/support/memory-leak$ make
Almost. It should be either: `tasks/...` or `guides/...`. I fixed my comment.

2024-04-05 18:12 UTC, teodutu requested changes
I made another high-level pass. Try adding the new files to `config.yaml` to render them and see how things look on the website.

2024-04-05 18:12 UTC, teodutu commented on chapters/data/process-memory/reading/process-memory.md
> +### Practice
Ditto: practice items should be made standalone under `drills/tasks/`.

2024-10-20 14:01 UTC, teodutu commented
Continued and implemented by #77.

2024-10-20 14:01 UTC, closed without merging