chapter/compute: Restructure repo according to updated methodology
cs-pub-ro/operating-systems pull request #74
Opened 2024-08-04 18:03 UTC by AndreiMiga77

# Prerequisite Checklist

- [ ] Read the [contribution guidelines](https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [ ] Tested your changes against relevant architectures and platforms;
- [ ] Updated relevant documentation (if needed).

## Description of changes

2024-08-05 19:51 UTC, teodutu requested changes
I made an initial, high-level pass. Fix my inline suggestions and the more general ones listed below (especially the one regarding building the site) and then I'll give this another look.

- Add the following line at the end of each task: `"If you're having difficulties solving this exercise, go through [this](link to the relevant section in reading/) reading material."`
- `use git rm -rf content/chapters/compute` to remove all remaining files in that folder once they're moved
- Squash your commits into a single one because `checkpatch` runs on all commits every time. Further amend this single commit and `git push -f` upon every new review without adding additional commits.

2024-08-05 19:51 UTC, teodutu commented on chapters/compute/threads/drills/tasks/multithreaded/README.md
Add the task statement here, don't leave this empty.

2024-08-05 19:51 UTC, teodutu commented on chapters/compute/threads/guides/sum-array/README.md
> +Each thread runs the `calculateArrayPartSum` function and then finishes.
```suggestion
Each thread runs the `calculate_array_part_sum()` function and then finishes.
```

2024-08-05 19:51 UTC, teodutu commented on config.yaml
> +
```suggestion
        - Processes:
            path: chapters/compute/processes/
            extra:
            - media/
            - drills/
            subsections:
            - Reading: reading/processes.md
            - Drills:
                path: drills/
                subsections:
                    - Tasks:
                        path: tasks/
                    - Questions:
                        path: questions/
                        subsections:
                            - Cause of FileNotFoundError: cause-of-file-not-found-error.md
                            - create_sleepy Process Ending: create-sleepy-process-ending.md
                            - Parent of sleep Processes: parent-of-sleep-processes.md
                            - Process Creation: process-creation.md
                            - Processes Speedup: process-speedup.md
        - Threads:
            path: chapters/compute/threads
            extra:
                - drills/
                - guides/
                - media/
            subsections:
                - Tasks:
                    path: tasks/
                - Questions:
                    path: questions/
                    subsections:
                        - Seg Fault Exit Code: seg-fault-exit-code.md
                        - Thread Memory: thread-memory.md
                        - Threads Shared Data: threads-shared-data.md
                - Guides:
                    path: guides/
        - Usage of Processes and Threads in apache2:
            path: chapters/compute/processes-threads-apache2
            extra:
                - drills/
                - guides/
            subsections:
                - Reading: reading/processes-threads-apache2.md
                - Drills:
                    path: drills/
                    subsections:
                        - Tasks:
                            path: tasks/
                            subsections:
                                - Investigate apache2 Using strace/: apache2/
                        - Questions:
                            path: questions/
                            subsections:
                                - apache2 Document Root: apache2-strace.md
                - Guides:
                    path: guides/
                    subsections:
                        - apache2 Live Action: apache2/
        - Copy-on-Write:
            path: chapters/compute/copy-on-write
            extra:
                - drills/
                - guides/
                - media/
            subsections:
                - Reading: reading/copy-on-write.md
                - Drills:
                    path: drills/
                    subsections:
                        - Questions:
                            path: questions/
                            subsections:
                                - Child Faults After Write: child-faults-after-write.md
                                - Parent Faults before fork(): parent-faults-before-fork.md
                                - Always Shared Sections: sections-always-shared.md
                - Guides:
                    path: guides/
                    subsections:
                        - Fork faults/: fork-faults/
        - Synchronization:
            path: chapters/compute/synchronization
            extra:
                - drills/
                - guides/
                - media/
            subsections:
                - Reading: reading/synchronization.md
                - Drills:
                    path: drills/
                    subsections:
                        - Tasks:
                            path: tasks/
                            subsections:
                                - C - TLS on Demand/: race-condition/
                        - Questions:
                            path: questions/
                            subsections:
                                - Coarse vs Granular Critical Section: coarse-vs-granular-critical-section.md
                                - Both Condition and Mutex: notify-only-with-mutex.md
                                - Not Race Condition: not-race-condition.md
                                - Semaphore Equivalent: semaphore-equivalent.md
                                - TLS Synchronization: tls-synchronization.md
                                - TLS var Copies: tls-var-copies.md
                - Guides:
                    path: guides/
                    subsections:
                        - apache2 Simulator/: apache2-simulator/
        - User-Level Threads:
            path: chapters/compute/user-level-threads
            extra:
                - drills/
                - guides/
            subsections:
                - Reading: reading/user-level-threads.md
                - Drills:
                    path: drills/
                    subsections:
                        - Questions:
                            path: questions/
                            subsections:
                                - Fiber Strace: fiber-strace.md
                                - Sleeping on a Fiber: sleeping-on-a-fiber.md
                - Guides:
                    path: guides/
                    subsections:
                        - Interaction Between Threads and Fibers/: user-level-threads/
        - Arena:
            path: chapters/compute/arena
            extra:
                - drills/
                - media/
            subsections:
                - Reading: reading/arena.md
                - Drills:
                    path: drills/
                    subsections:
                        - Tasks:
                            path: tasks/
                        - Questions:
                            path: questions/
                            subsections:
                                - exec() Without fork(): exec-without-fork.md
                                - Mini-shell Stops After Command: mini-shell-stops-after-command.md
                                - Copy-on-write Flag for mmap(): mmap-cow-flag.md
                                - Who Calls execve in the Log of the Parent Process?: who-calls-execve-parent.md
```

The build failed because some subchapters were indented 1 space too little to the left and because you used backticks in the sidebar titles. This config doesn't allow special characters. It fails after making the changes above because it can't find some of the files. Make sure you have the right paths.

2024-09-18 10:20 UTC, teodutu requested changes
I gave you the fixes to `config.yaml` so the website builds properly. Apply them, then take care of my other suggestions.

- Change this line [1] to `- 'chapters/compute/**/*'` so the PR label for `topic/compute` is assigned correctly.
- Remove the `arena/` folder. Extract all tasks from it and place them in whatever subchapter they fit best under `drills/tasks/`. You can prefix their names with "BONUS - " in `config.yaml` if they're more difficult.
- Add the following line at the end of each task: `"If you're having difficulties solving this exercise, go through [this](link to the relevant section in reading/) reading material."`

[1] https://github.com/cs-pub-ro/operating-systems/blob/eb0056b7d6aac2c5ecd35b911e181f4e46b8bd86/.github/labeler.yml#L8

2024-09-18 10:20 UTC, teodutu commented on config.yaml
> +
```suggestion
        - Compute:
            subsections:
              - Slides: /build/embed_reveal/Compute/Compute.mdx
              - Overview:
                  path: chapters/compute/overview/
                  extra:
                    - media/
                  subsections:
                    - Reading: reading/overview.md
              - Hardware Perspective:
                  path: chapters/compute/hardware-perspective/
                  extra:
                    - media/
                  subsections:
                    - Reading: reading/hardware-perspective.md
              - Processes:
                  path: chapters/compute/processes/
                  extra:
                    - media/
                    - drills/
                  subsections:
                  - Reading: reading/processes.md
                  - Drills:
                      path: drills/
                      subsections:
                          - Tasks:
                              path: tasks/
                          - Questions:
                              path: questions/
                              subsections:
                                  - Cause of FileNotFoundError: cause-of-file-not-found-error.md
                                  - create_sleepy Process Ending: create-sleepy-process-ending.md
                                  - Parent of sleep Processes: parent-of-sleep-processes.md
                                  - Process Creation: process-creation.md
                                  - Processes Speedup: process-speedup.md
              - Threads:
                  path: chapters/compute/threads
                  extra:
                    - drills/
                    - guides/
                    - media/
                  subsections:
                    - Tasks:
                        path: tasks/
                    - Questions:
                        path: questions/
                        subsections:
                          - Seg Fault Exit Code: seg-fault-exit-code.md
                          - Thread Memory: thread-memory.md
                          - Threads Shared Data: threads-shared-data.md
                    - Guides:
                        path: guides/
              - Usage of Processes and Threads in apache2:
                  path: chapters/compute/processes-threads-apache2
                  extra:
                    - drills/
                    - guides/
                  subsections:
                    - Reading: reading/processes-threads-apache2.md
                    - Drills:
                        path: drills/
                        subsections:
                          - Tasks:
                              path: tasks/
                              subsections:
                                - Investigate apache2 Using strace/: apache2/
                          - Questions:
                              path: questions/
                              subsections:
                                - apache2 Document Root: apache2-strace.md
                    - Guides:
                        path: guides/
                        subsections:
                          - apache2 Live Action: apache2/
              - Copy-on-Write:
                  path: chapters/compute/copy-on-write
                  extra:
                    - drills/
                    - guides/
                    - media/
                  subsections:
                    - Reading: reading/copy-on-write.md
                    - Drills:
                        path: drills/
                        subsections:
                            - Questions:
                                path: questions/
                                subsections:
                                  - Child Faults After Write: child-faults-after-write.md
                                  - Parent Faults before fork(): parent-faults-before-fork.md
                                  - Always Shared Sections: sections-always-shared.md
                    - Guides:
                        path: guides/
                        subsections:
                          - Fork faults/: fork-faults/
              - Synchronization:
                path: chapters/compute/synchronization
                extra:
                  - drills/
                  - guides/
                  - media/
                subsections:
                  - Reading: reading/synchronization.md
                  - Drills:
                      path: drills/
                      subsections:
                        - Tasks:
                            path: tasks/
                            subsections:
                              - C - TLS on Demand/: race-condition/
                        - Questions:
                            path: questions/
                            subsections:
                              - Coarse vs Granular Critical Section: coarse-vs-granular-critical-section.md
                              - Both Condition and Mutex: notify-only-with-mutex.md
                              - Not Race Condition: not-race-condition.md
                              - Semaphore Equivalent: semaphore-equivalent.md
                              - TLS Synchronization: tls-synchronization.md
                              - TLS var Copies: tls-var-copies.md
                  - Guides:
                      path: guides/
                      subsections:
                        - apache2 Simulator/: apache2-simulator/
              - User-Level Threads:
                  path: chapters/compute/user-level-threads
                  extra:
                      - drills/
                      - guides/
                  subsections:
                      - Reading: reading/user-level-threads.md
                      - Drills:
                          path: drills/
                          subsections:
                              - Questions:
                                  path: questions/
                                  subsections:
                                      - Fiber Strace: fiber-strace.md
                                      - Sleeping on a Fiber: sleeping-on-a-fiber.md
                      - Guides:
                          path: guides/
                          subsections:
                              - Interaction Between Threads and Fibers/: user-level-threads/
              - Arena:
                  path: chapters/compute/arena
                  extra:
                      - drills/
                      - media/
                  subsections:
                      - Reading: reading/arena.md
                      - Drills:
                          path: drills/
                          subsections:
                              - Tasks:
                                  path: tasks/
                              - Questions:
                                  path: questions/
                                  subsections:
                                      - exec() Without fork(): exec-without-fork.md
                                      - Mini-shell Stops After Command: mini-shell-stops-after-command.md
                                      - Copy-on-write Flag for mmap(): mmap-cow-flag.md
                                      - Who Calls execve in the Log of the Parent Process?: who-calls-execve-parent.md
```
Change to this config to get rid of the formatting errors. Pay very close attention to spacing. Use 2-space tabs and make sure you respect the exact structure from the Software Stack chapter. No extra or missing tabs.

The build will still fail because you have a bunch of broken links. Run the `make build` command and that will give you a list of missing files. Fix them and then the build should work.

After you get the build to work, restructure the config to split the contact into 3 labs with the following subchapter:

- Lab 6: [Hardware Perspective - Threads]
- Lab 7: [Apache 2 - Copy-on-Write]
- Lab 8: [Synchroni [...]

2024-10-23 09:35 UTC, Alex-deVis commented
@teodutu, @razvand, @VladNastase I finished the directory structure change but the builder seems to fail (check action for logs). From what I understand, it complains that some media files are invalid. This is very weird since `Software Stack/media`, `Data/media`, and `Compute/media` are all copies of `.view/media` (generated with `gen-view.py`).
```
The image at "/build/docusaurus/SO/docs/Data/media/exec.svg" can't be read correctly. Please ensure it's a valid image.
unsupported file type: undefined (file: /build/docusaurus/SO/docs/Data/media/exec.svg)
```

The media paths are defined with `extra: media/` in the `config.yaml` for each chapter. I will not be able to debug this week, so feel free to investigate, or leave suggestions on how to go about this.

2024-10-24 07:49 UTC, Alex-deVis commented
It seems there were other issues I missed:
> Warning: nedu_builder.plugins.docusaurus:STDERR: [WARNING] Duplicate routes found!
- Attempting to create page at /operating-systems/74/Compute/, but a page already exists at this route.
- Attempting to create page at /operating-systems/74/Data/, but a page already exists at this route.

This error makes no sense, I ran `make clean build` and did not change the `Data` chapter. We should look into this.

The real problem seems to be:
> Error: Image docs/Data/media/100-percent-cpu.jpeg used in docs/Compute/lab6.md not found.
    at async Promise.all (index 2)

It was either this or solving the dangling references in the .md files.

2024-10-27 10:08 UTC, teodutu requested changes
I only found one rendering issue. Fix that and then I'm OK with this.

2024-10-27 10:08 UTC, teodutu commented on chapters/compute/synchronization/drills/tasks/race-condition/README.md
> +    [Quiz 2](../../questions/tls-var-copies.md)
These quizzes render like a block of code. Maybe try to remove 2 spaces or the tab altogether?

2024-10-27 11:23 UTC, teodutu requested changes

2024-10-27 11:23 UTC, teodutu commented on chapters/compute/synchronization/drills/tasks/race-condition/README.md
> +This is because, upon creating a new thread, its TLS is initialised.
```suggestion
2. Print the address and value of `var` in each thread.
See that they differ.

3. Modify the value of `var` in the `main()` function before calling `pthread_create()`.
Notice that the value doesn't propagate to the other threads.
This is because, upon creating a new thread, its TLS is initialised.
```
Now because you removed the indent above, these list items aren't numbered properly because there's a break in the list. Just number them manually, I guess.

2024-10-27 11:26 UTC, Alex-deVis commented on chapters/compute/synchronization/drills/tasks/race-condition/README.md
> +This is because, upon creating a new thread, its TLS is initialised.
No, I think I just have to indent the subsequent phrases.
```
1. Print the address and value of `var` in each thread.
See that they differ.
```
should be written as:
```
1. Print the address and value of `var` in each thread.
  See that they differ.
```

2024-10-27 11:26 UTC, Alex-deVis commented on chapters/compute/synchronization/drills/tasks/race-condition/README.md
> +This is because, upon creating a new thread, its TLS is initialised.
Ignore this, I misread your comment.

2024-10-27 11:34 UTC, Alex-deVis commented on chapters/compute/synchronization/drills/tasks/race-condition/README.md
> +This is because, upon creating a new thread, its TLS is initialised.
OK, so the problem was that quizzes had the wrong indent. Seems like markdown expects `3 spaces` indentation when you are under a numbered list.

2024-10-27 11:51 UTC, teodutu approved these changes

2024-10-27 11:51 UTC, merged