Add IO to OpenEducation methodology
cs-pub-ro/operating-systems pull request #75
Opened 2024-08-05 00:19 UTC by Mihnea0Firoiu

# Prerequisite Checklist

- [ ] Read the [contribution guidelines](https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [ ] Tested your changes against relevant architectures and platforms;
- [ ] Updated relevant documentation (if needed).

## Description of changes

2024-08-11 05:16 UTC, teodutu requested changes
Check my comments to see some easy first fixes and also why the build fails. Then when it passes I'll make a more in-depth review.

- Move the task descriptions from the `reading/` files to each task's `README.md`
- Remove references to the common makefiles (`.../common/makefile/*.mk`). Copy their content to each makefile that includes them so the tasks don't depend on outside resources.

2024-09-29 15:36 UTC, teodutu reviewed
The build fails because `chapters/io/arena/drills/tasks/mini-shell/` is missing its `support/` folder which causes the Makefile symlink to point to an invalid path.

2024-09-29 16:15 UTC, teodutu requested changes

2024-09-29 16:15 UTC, teodutu commented on chapters/io/remote-io/drills/tasks/receive-challenges/support/Makefile
Remove the `include` and copy-paste the contents of the included makefile here so the task doesn't have outside dependencies.

2024-09-29 16:15 UTC, teodutu commented on chapters/io/remote-io/drills/tasks/send-receive/support/receiver.py
> +PORT = 5000  # Port to listen for data data on (non-privileged ports are > 1023)
```suggestion
PORT = 5000  # Port to listen for data (non-privileged ports are > 1023)
```

2024-10-22 18:40 UTC, fabianpatras commented on chapters/io/io-internals/drills/tasks/buffering/support/libc_buffering.c
> +/* SPDX-License-Identifier: BSD-3-Clause */
Why is this? (`//` vs `/* ... */`)

2024-10-22 18:48 UTC, teodutu commented on chapters/io/io-internals/drills/tasks/buffering/support/libc_buffering.c
> +/* SPDX-License-Identifier: BSD-3-Clause */
That's what checkpatch wants. I found this explanation, but I can't verify whether this is the main reason: https://github.com/ARM-software/tf-issues/issues/581#issuecomment-384960884

2024-10-22 18:58 UTC, fabianpatras commented on chapters/io/io-internals/drills/tasks/buffering/support/libc_buffering.c
> +/* SPDX-License-Identifier: BSD-3-Clause */
Yeah, that's what the checkpatch wants which is following this style:

```
C source: // SPDX-License-Identifier: <SPDX License Expression>
C header: /* SPDX-License-Identifier: <SPDX License Expression> */
[...]

If a specific tool cannot handle the standard comment style, then the appropriate comment mechanism which the tool accepts shall be used.
This is the reason for having the "/* */" style comment in C header files.
There was build breakage observed with generated .lds files where 'ld' failed to parse the C++ comment.
This has been fixed by now, but there are still older assembler tools which cannot handle C++ style comments.
```
Cited from https://github.com/torvalds/linux/blob/master/Documentation/process/license-rules.rst#license-identifier-syntax

2024-10-22 19:01 UTC, teodutu commented on chapters/io/io-internals/drills/tasks/buffering/support/libc_buffering.c
> +/* SPDX-License-Identifier: BSD-3-Clause */
But what you quoted explains why headers use C-style comments, not why source files use the C++-style.

2024-11-08 07:27 UTC, Alex-deVis commented
@razvand, since I also made changes to the content itself, I think you should also review this.

2024-11-22 20:11 UTC, teodutu requested changes
Why does this PR remove files from the `compute/` and `data/` chapters?

2024-11-22 20:11 UTC, teodutu commented on chapters/io/file-descriptors/drills/tasks/my-cat/README.md
> +Navigate to `file-descriptors/drills/tasks/my-cat/support/src` and checkout `my_cat.c`.
```suggestion
Navigate to `chapters/io/file-descriptors/drills/tasks/my-cat/support/src` and checkout `my_cat.c`.
```
Use full paths just to be sure.

2024-11-22 20:14 UTC, teodutu commented on chapters/io/file-descriptors/drills/tasks/my-cat/solution/my_cat.c
> +	return totalBytesRead;
Convert these variables to `snake_case`. Do the same for the functions below.

2024-11-25 22:50 UTC, teodutu requested changes

2024-11-25 22:50 UTC, teodutu commented on chapters/io/ipc/drills/tasks/receive-challenges/README.md
> +Navigate to `chapters/io/ipc/drills/tasks/receive-challenges` and run `make` to generate the `support` directory.
Remember to add the script, Makefile and `solution/` folder. And remove `support/`.

2024-11-25 22:50 UTC, teodutu commented on chapters/io/optimizations/drills/tasks/multiplexed-client-server/README.md
> +Navigate to `chapters/io/optimizations/drills/tasks/client-server-epoll` and run `make` to generate the `support` files.
```suggestion
Navigate to `chapters/io/optimizations/drills/tasks/multiplexed-client-server` and run `make` to generate the `support` files.
```

2024-11-27 08:35 UTC, Alex-deVis commented
> Why does this PR remove files from the compute/ and data/ chapters?

Generic stuff such as removing `utils/sock` if unused and fixing links. Take a look for yourself:
```
$ git diff main $(git diff --name-only main . | egrep -v sock_util | grep compute)
```

2024-11-27 09:15 UTC, teodutu commented
I think you forgot to add a file or messed up its name: https://github.com/cs-pub-ro/operating-systems/actions/runs/12047113855/job/33588983238#step:6:227

2024-11-27 10:14 UTC, Alex-deVis commented
> I think you forgot to add a file or messed up its name: https://github.com/cs-pub-ro/operating-systems/actions/runs/12047113855/job/33588983238#step:6:227

I have no idea what happened - seems like the `shared-memory` task is not present in the current `copy-on-write` lab. Is this intended? I readded it to solve the issue.

2024-11-27 17:16 UTC, teodutu requested changes
The slides are still empty [1] because you forgot to add the `slides/` folders in each subchapter.

[1] https://cs-pub-ro.github.io/operating-systems/75/IO/

2024-11-27 21:48 UTC, Alex-deVis commented
> The slides are still empty [1] because you forgot to add the slides/ folders in each subchapter.

It was a subtle metaphor for the need of I/O. Anyway, check again.

2024-11-28 21:34 UTC, teodutu approved these changes
Fuck that Java error.

2024-11-28 21:35 UTC, merged