Modify app-interact chapter
cs-pub-ro/operating-systems pull request #76
Opened 2024-08-05 19:19 UTC by SorinAlexB

# Prerequisite Checklist

- [ ] Read the [contribution guidelines](https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [ ] Tested your changes against relevant architectures and platforms;
- [ ] Updated relevant documentation (if needed).

## Description of changes

2024-08-07 16:14 UTC, teodutu requested changes
The build fails because you made some indentation errors in `config.yaml`. However, I reckon its format isn't the most user-friendly. I made a comment explaining how to fix them.

I skimmed through the overall structure and pointed out a few things to change. I'll look deeper into the content once the website can be built (I also suggested how to do that). In addition to these changes, modify your commit message to:
```
chapter/app-interact: Restructure the chapter according to OpenEducationHub methodology

<add a description here>
```

2024-08-07 16:14 UTC, teodutu commented on config.yaml
> +                                  - Timer: timer.md
Change this section to the following. Be mindful of indentations: each subsection must be precisely 2 spaces further than the previous one. And don't leave sections with just a `path` component.

```yaml
      - Application Interaction:
          - Lab 12 - Application Interaction:
              subsections:
                - Overview:
                    path: chapters/app-interact/overview/
                    subsections:
                      - Reading: reading/overview.md
                - Time Server:
                    path: chapters/app-interact/time-server
                    extra:
                      - drills/questions/
                      - drills/tasks/
                    subsections:
                      - Reading: reading/time-server.md
                      - Drills:
                          path: drills/
                          subsections:
                            - Tasks:
                                path: tasks/
                                subsections:
                                  - Time Server/: time-server/
                            - Questions:
                                path: questions/
                                subsections:
                                  - Time Server: time-server.md
                                  - Time Server Interoperability: time-server-interop.md
                - Password Cracker:
                    path: chapters/app-interact/password-cracker
                    extra:
                      - drills/tasks/
                    subsections:
                      - Reading: reading/password-cracker.md
                      - Drills:
                          path: drills/
                          subsections:
                            - Tasks:
                                path: tasks/
                                subsections:
                                  - Password Cracker/: password-cracker/
                - The X Window System:
                    path: chapters/app-interact/x-window-system
                    extra:
                      - media/
                    subsections:
                      - Reading: reading/x-window-system.md
                - D-Bus:
                    path: chapters/app-interact/dbus
                    extra:
                      - media/
                    subsections:
                      - Reading: reading/dbus.md
                - OS Cloud:
                    path: chapters/app-interact/os-cloud
                    extra:
                      - media/
                      - drills/questions/
                      - drills/tasks/
                    subsections:
                      - Reading: reading/os-cloud.md
                      - Drills:
                          path: drills/
                          subsections:
                            - Tasks:
                                path: tasks/
                                subsections:
                                  - OS Cloud/: os-cloud/
                            - Questions:
                                path: questions/
                                subsections:
                                  - Cgroups versus namespaces: cgroups-vs-namespaces.md
                                  - Container versus VM: container-vs-vm.md
                                  - VM Creation: vm-creation.md
                - Arena:
                    path: chapters/app-interact/arena
                    extra:
                      - media/
                      - drills/questions/
                      - drills/tasks/
                    subsections:
                      - Reading: reading/arena.md
                      - Drills:
                          path: drills/
                          subsections:
                            - Tasks:
                                path: tasks/
                                subsections:
                                  - Dbus/: dbus/
                            - Questions:
                                path: questions/
                                subsections:
                                  - Timer: timer.md
```

Then add the following files that the builder won't be able to find:

```
- Application Interaction/Lab 12 - Application Interaction/Arena/Drills/Tasks/Dbus/README
- Application Interaction/Lab 12 - Application Interaction/OS Cloud/Drills/Tasks/OS Cloud/README
- Application Interaction/Lab 12 - Application Interaction/Password Cracker/Drills/Tasks/Password Cracker/README
- Application Interaction/Lab 12 - Application Interaction/Time Server/Drills/Tasks/Time Server/README
```

2024-09-14 07:24 UTC, teodutu requested changes
This diff is so huge that it's difficult to load. Remove the `output` folder altogether and add it to the global `.gitignore` file. This will reduce the size of your diff significantly. Then I'll return with a more in-depth review.

2024-09-14 07:24 UTC, teodutu commented on chapters/app-interact/os-cloud/drills/tasks/os-cloud/README.md
Move the "Practice" sections from  the `reading/` sections to each `task`'s readme.

2024-09-18 10:54 UTC, teodutu requested changes
The lab content looks alright. Perhaps you can rename it to something more accurate such as "Investigate Applications". Also see my suggestions below inline. 

- You also need to move the slides from `content/chapters/app-interact/lecture` to `chapters/app-interact/<inidivual-subchapters>/slides/`
- Add the following line to the end of each task's `README.md`: "If you're having difficulties solving this task, go through [this](link to the relevant section in reading/) reading material."
- Mention the path to the support files in each task so students can get there more easily.

2024-09-18 10:54 UTC, teodutu commented on chapters/app-interact/os-cloud/drills/tasks/os-cloud/README.md
Move this task to `guides/` because there's nothing for students to do individually and the `README.md` gives a complete rundown of what they're supposed to do.

2024-09-18 10:54 UTC, teodutu commented on chapters/app-interact/password-cracker/drills/tasks/password-cracker/README.md
> +Check that the `worker` function is indeed called from different worker processes.
```suggestion
Check that the `worker()` function is indeed called from different worker processes.
```

2024-09-18 10:54 UTC, teodutu commented on chapters/app-interact/password-cracker/drills/tasks/password-cracker/README.md
> +To get the current process ID, use the `getpid` function from the `os` module.
```suggestion
To get the current process ID, use the `getpid()` function from the `os` module.
```

2024-12-14 12:59 UTC, Alex-deVis commented
Superseded by #137.

2024-12-14 12:59 UTC, closed without merging