Restructure data
cs-pub-ro/operating-systems pull request #77
Opened 2024-09-13 16:50 UTC by Dragosh-C

# Prerequisite Checklist

- [x] Read the [contribution guidelines](https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [ ] Tested your changes against relevant architectures and platforms;
- [ ] Updated relevant documentation (if needed).

## Description of changes

- Integrated drills folder with the files (tasks and questions) into the Arena lab.
- Modified config.yaml to ensure the lab is displayed correctly on the webpage

2024-09-13 18:25 UTC, teodutu requested changes
Without looking at the code yet, the first thing you'll need to do is to squash all these commits into a single one:

```
$ git rebase -i HEAD~5
```
This will open your default editor and list the last 5 commits. Replace the word `pick` from the beginning of each line with `s` from squash, then save and exit.

Another editor window will appear with all 5 commit messages concatenated. Delete them and reword the commit similarly to this one: https://github.com/cs-pub-ro/operating-systems/commit/c58a60b3f2d61669e7ee44e17b13ef72434b6431

```
chapters/data: Restructure content according to updated methodology

Then add a description of your changes below

<don't remove your signature at the end>
```

2024-09-14 06:54 UTC, teodutu requested changes
Nice work so far. Now you need to add the drills, slides and all other components from the old folder [1] to their corresponding subchapter [2]. You'll be able to remove [1] afterwards. And the arena should be split into the aforementioned subchapters. So every exercise from the arena must be moved to the subchapter that's closest to it (and follow the same folder organisation).

[1] https://github.com/cs-pub-ro/operating-systems/tree/main/content/chapters/data
[2] https://github.com/Dragosh-C/operating-systems/tree/restructure-data/chapters/data

2024-09-24 12:09 UTC, teodutu commented on chapters/data/working-with-memory/drills/guides/memory-alloc/README.md
> +Navigate to the `memory-alloc/support/` directory.
```suggestion
Navigate to the `guides/memory-alloc/support/` directory.
```

2024-09-24 12:09 UTC, teodutu commented on chapters/data/working-with-memory/drills/guides/memory-alloc/README.md
> +You can observe that all allocations are performed via `malloc` and the memory is freed using `free`.
```suggestion
You can observe that all allocations are performed via `malloc()` and the memory is freed using `free()`.
```
This helps distinguish functions from simple labels, variables or file names.

2024-09-24 12:10 UTC, teodutu commented on chapters/data/working-with-memory/drills/guides/memory-alloc/README.md
> +In D, both worlds are combined: variables may be allocated manually on the stack/heap or allocated via the garbage collector (for brevity, `malloc`-based allocation is not presented in this example).
```suggestion
In D, both worlds are combined: variables may be allocated manually on the stack/heap or via the garbage collector (for brevity, `malloc()`-based allocation is not presented in this example).

2024-09-24 12:11 UTC, teodutu commented on chapters/data/working-with-memory/drills/guides/memory-vuln/README.md
> +
```suggestion

```

2024-09-24 12:13 UTC, teodutu commented on chapters/data/working-with-memory/drills/guides/memory-alloc/README.md
Move all guides one directory up the hierarchy so that it looks like this:
```
working-with-memory/
|-- guides/
|   `-- ...
|-- drills/
|   |-- tasks/
|   |   `-- ...
|   `-- questions/
|       `-- ...
|-- media/
...
```

2024-09-24 12:22 UTC, teodutu commented on chapters/data/working-with-memory/drills/questions/memory-access.md
> +What happens if we introduce the code `cp[2] = 't'` in the program located in the `memory-access/mem_access.c` file?
```suggestion
What happens if we introduce the code `cp[2] = 't'` in the program located in the `drills/tasks/memory-access/mem_access.c` file?
```
Make sure the links start from the subchapter folder so students know where to find the files (some may be guides, others tasks).

2024-09-24 12:23 UTC, teodutu commented on chapters/data/working-with-memory/drills/tasks/memory-protection/README.md
> +Let's navigate to the `memory-protection/support/` directory and inspect the `mem_prot.c` source file.
```suggestion
Let's navigate to the `drills/tasks/memory-protection/support/` directory and inspect the `mem_prot.c` source file.
```

2024-09-24 12:23 UTC, teodutu commented on chapters/data/working-with-memory/drills/guides/memory-vuln/README.md
> +Navigate to the `memory-vuln/support/` directory.
```suggestion
Navigate to the `guides/memory-vuln/support/` directory.
```

2024-09-24 12:27 UTC, teodutu commented on chapters/data/working-with-memory/drills/tasks/memory-protection/README.md
> +no execute permissions.
Move these lines to `reading/working-with-memory.md`.

2024-09-24 12:28 UTC, teodutu commented on chapters/data/working-with-memory/drills/tasks/memory-access/README.md
> +Navigate to the `memory-access/support/` directory.
```suggestion
Navigate to the `drills/tasks/memory-access/support/` directory.
```

2024-09-24 12:30 UTC, teodutu commented on chapters/data/working-with-memory/drills/tasks/memory-access/README.md
> +By using this triplet, the content of a variable is stored, retrieved or rewritten.
Move these lines to `reading/working-with-memory.md`.

2024-09-30 07:56 UTC, teodutu requested changes
The content you've added so far is good. Remember to split the arena content among the other subchapters. Lab 5 should be "Memory Security". After you do this, remove the `content/chapters/data` folder completely, together with any mentions of it in `config.yaml`.

2024-10-01 20:42 UTC, teodutu commented on chapters/data/perspectives/slides/perspectives-of-data.md
> +![Data3](../media/lvl-data.svg)
```suggestion
![Data3](perspectives/media/lvl-data.svg)
```
Change all links to `media/` items from slides from `../media/...` to `<subchapter-name>/media/...`. This is needed because they need to work from `slides.md` which is created inside `chapters/data/` from `slides.mdpp`.

I'll add the rest of my review in 2-3 days.

2024-10-07 15:48 UTC, teodutu requested changes
This is nearly done. After feedback from the first lab, we figured out it would be best to use the full paths starting from `chapters/...` when instructing students to navigate to a certain folder. After that, just fix the linter failures [1] and this might work fine and rebase the `main` branch because there have been several changes to `config.yaml` made in the meantime.

[1] https://github.com/cs-pub-ro/operating-systems/pull/77/checks

2024-10-07 15:48 UTC, teodutu commented on chapters/data/investigate-memory/guides/app-investigation-deluge/README.md
> +student@os:~/.../lab/support/deluge$ cd deluge/core/
```suggestion
student@os:~/.../app-investigation$ git clone https://github.com/deluge-torrent/deluge
Cloning into 'deluge'...
[...]

student@os:~/.../app-investigation$ cd deluge/

student@os:~/.../lab/support/deluge$ ls
AUTHORS       deluge      docs             gen_web_gettext.py  MANIFEST.in       msgfmt.py  pyproject.toml  requirements-dev.txt    requirements.txt  setup.py  version.py
CHANGELOG.md  DEPENDS.md  generate_pot.py  LICENSE             minify_web_js.py  packaging  README.md       requirements-tests.txt  setup.cfg         tox.ini
```

And enter the `deluge/core/` subdirectory:

```console
student@os:~/.../app-investigation/deluge$ cd deluge/core/
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/investigate-memory/guides/d-allocator/README.md
> +student@os:~/.../lab/support/phobos$ cd std/experimental/allocator/
```suggestion
student@os:~/.../d-allocator$ git clone https://github.com/dlang/phobos
[...]

student@os:~/.../d-allocator$ cd phobos/

student@os:~/.../d-allocator/phobos$ ls
azure-pipelines.yml  changelog  CODEOWNERS  CONTRIBUTING.md  dub.sdl  etc  index.dd  LICENSE_1_0.txt  posix.mak  project.ddoc  README.md  std  test  unittest.d  win32.mak  win64.mak
```

And enter `std/experimental/allocator/` to browse information about the allocator:

```console
student@os:~/.../d-allocator/phobos$ cd std/experimental/allocator/
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/investigate-memory/guides/git/README.md
> +student@os:~/.../lab/support/git$ grep -rc 'xmalloc(' . | grep -v ':0' | sort -n -t ':' -k 20
```suggestion
student@os:~/.../git$ git clone https://github.com/git/git
[...]

student@os:~/.../git$ cd git/
```

We look of uses of `malloc()`:

```console
student@os:~/.../git/git$ grep -r 'malloc(' .
```

We see there are multiple calls to the `xmalloc()` function, which is likely a wrapper for `malloc()`.
We search for the definition of `xmalloc()`:

```console
student@os:~/.../git/git$ grep -rn 'xmalloc(' . | grep -v ';'
./commit.c:188:                 graft = xmalloc(st_add(sizeof(*graft),
./add-interactive.c:157:        list->sorted.items = xmalloc(st_mult(sizeof(*list->sorted.items),
./Documentation/RelNotes/2.24.0.txt:91: * xmalloc() used to have a mechanism to ditch memory and address
./Documentation/RelNotes/2.24.0.txt:210:   xmalloc() wrapper, as the rest of the system, for consistency.
./Documentation/RelNotes/2.34.0.txt:230: * mmap() imitation used to call xmalloc() that dies upon malloc()
./Documentation/RelNotes/2.33.1.txt:44: * mmap() imitation used to call xmalloc() that dies upon malloc()
./diffcore-delta.c:56:  new_spanhash = xmalloc(st_add(sizeof(*orig),
./diffcore-delta.c:135: hash = xmalloc(st_add(sizeof(*hash),
./kwset.c:41:/* adapter for `xmalloc()`, which takes `size_t`, not `long` */
./builtin/fast-import.c:461:    b = xmalloc(sizeof(struct object_entry_pool)
./hashmap.h:311: * your structure was allocated with xmalloc(), you can just free(3) it,
./xdiff/xdiff.h:122:#define xdl_malloc(x) xmalloc(x)
./wrapper.c:45:static void *do_xmalloc(size_t size, int gentle)
./wrapper.c:70:void *xmalloc(size_t size)
./contrib/credential/wincred/git-credential-wincred.c:26:static void *xmalloc(size_t size)
Binary file ./.git/objects/pack/pack-c587b9f11a82bc4d49848d74132e60ea4dbeb177.pack matches
./git-compat-util.h:1046:# define xalloca(size)      (xmalloc(size))
./git-compat-util.h:1086:#define ALLOC_ARRAY(x, alloc) (x) = xmalloc(st_mult(sizeof(*(x)), (alloc)))
./read-cache.c:3768:    ieot = xmalloc(sizeof(struct index_entry_offset_table)
```

Line `./wrapper.c:70` is the one with the definition of the `xmalloc()` function.
It makes a call of the [`do_xmalloc()` function](https://github.com/git/git/blob/master/wrapper.c#L45), that makes extra checks.
Also, if the `XMALLOC_POISON` macro is defined, all the allocated data is overwritten with a "poison" value (`0xA5`).
This is useful for early detection of memory-related issues, although, evidently, it adds overhead.

We can look for parts of the source code with the largest number of uses of `xmalloc()`:

```console
student@os:~/.../git/git$ grep -rc 'xmalloc(' . | grep -v ':0' | sort -n -t ':' -k 20
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/investigate-memory/guides/jemalloc/README.md
> +student@os:~/.../lab/support/memory-leak$ LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so MALLOC_CONF="stats_print:true" /bin/ps
```suggestion
student@os:~/.../jemalloc$ sudo apt -y install libjemalloc-dev
```

Note that this installs the distribution package, not the latest one (that may provide more features).

With this in place, we can use `jemalloc` against our pre-built executables or system executables (such as `ls`, `ps`).
We can test it against the executable files from `support/memory-leak/`:

```console
student@os:~/.../jemalloc$ LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so ./memory_leak_malloc
Andrei Popescu is 22 years old and likes Linux
Ioana David is 23 years old and likes macOS
```

`jemalloc` can use the `MALLOC_CONF` environment variable for a [diverse set of configurations](https://www.freebsd.org/cgi/man.cgi?query=malloc.conf).
For example, by using `stats_print:true` we print out information regarding the use of the library functions:

```console
student@os:~/.../jemalloc$ LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so MALLOC_CONF="stats_print:true" ./memory_leak_malloc
Andrei Popescu is 22 years old and likes Linux
Ioana David is 23 years old and likes macOS
___ Begin jemalloc statistics ___
Version: 3.6.0-11
Assertions disabled
Run-time option settings:
  opt.abort: false
  opt.lg_chunk: 22
  opt.dss: "secondary"
  opt.narenas: 32
  opt.lg_dirty_mult: 3
  opt.stats_print: true
  opt.junk: false
  opt.quarantine: 0
  opt.redzone: false
[...]
dirty pages: 26:0 active:dirty, 0 sweeps, 0 madvises, 0 purged
            allocated      nmalloc      ndalloc    nrequests
small:          72672          114            0            3
large:          32768            1            0            1
total:         105440          115            0            4
active:        106496
mapped:       4194304
[...]
```

`jemalloc` doesn't work against system executables using preloading, likely because of security options disabling the use of the library:

```console
student@os:~/.../jemalloc$ LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so MALLOC_CONF="stats_print:true" /bin/ls
Makefile  memory_leak  memory_leak.cpp  memory_leak_malloc  memory_leak_malloc.c  memory_leak_malloc.o  memory_leak.o

student@os:~/.../jemalloc$ LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so MALLOC_CONF="stats_print:true" /bin/ps
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/investigate-memory/guides/memory-actions/README.md
> +student@os:~/.../lab/support/memory-leak$ valgrind bash -c 'echo "ha"'
```suggestion
student@os:~/.../memory-actions$ valgrind ls
==24669== Memcheck, a memory error detector
==24669== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==24669== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==24669== Command: ls
==24669==
Makefile  memory_leak  memory_leak.cpp  memory_leak_malloc  memory_leak_malloc.c  memory_leak_malloc.o  memory_leak.o
==24669==
==24669== HEAP SUMMARY:
==24669==     in use at exit: 21,696 bytes in 14 blocks
==24669==   total heap usage: 51 allocs, 37 frees, 61,331 bytes allocated
==24669==
==24669== LEAK SUMMARY:
==24669==    definitely lost: 0 bytes in 0 blocks
==24669==    indirectly lost: 0 bytes in 0 blocks
==24669==      possibly lost: 0 bytes in 0 blocks
==24669==    still reachable: 21,696 bytes in 14 blocks
==24669==         suppressed: 0 bytes in 0 blocks
==24669== Rerun with --leak-check=full to see details of leaked memory
==24669==
==24669== For counts of detected and suppressed errors, rerun with: -v
==24669== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

student@os:~/.../memory-actions$ valgrind ps
==24671== Memcheck, a memory error detector
==24671== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==24671== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==24671== Command: ps
==24671==
  PID TTY          TIME CMD
24671 pts/22   00:00:00 memcheck-amd64-
26732 pts/22   00:00:01 bash
==24671==
==24671== HEAP SUMMARY:
==24671==     in use at exit: 264,929 bytes in 25 blocks
==24671==   total heap usage: 692 allocs, 667 frees, 334,268 bytes allocated
==24671==
==24671== LEAK SUMMARY:
==24671==    definitely lost: 0 bytes in 0 blocks
==24671==    indirectly lost: 0 bytes in 0 blocks
==24671==      possibly lost: 0 bytes in 0 blocks
==24671==    still reachable: 264,929 bytes in 25 blocks
==24671==         suppressed: 0 bytes in 0 blocks
==24671== Rerun with --leak-check=full to see details of leaked memory
==24671==
==24671== For counts of detected and suppressed errors, rerun with: -v
==24671== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

student@os:~/.../memory-actions$ valgrind bash -c 'echo "ha"'
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/investigate-memory/guides/memory-leak/README.md
> +student@os:~/.../lab/support/memory-leak$ mtrace ./memory_leak_malloc mem.trace
```suggestion
student@os:~/.../memory-leak$ make
g++    -c -o memory_leak.o memory_leak.cpp
cc   memory_leak.o  -lstdc++ -o memory_leak
cc    -c -o memory_leak_malloc.o memory_leak_malloc.c
cc   memory_leak_malloc.o  -lstdc++ -o memory_leak_malloc
```

Running them yields similar output:

```console
student@os:~/.../memory-leak$ ./memory_leak
Andrei Popescu is 22 years old and likes Linux
Ioana David is 23 years old and likes macOS
student@os:~/.../memory-leak$ ./memory_leak_malloc
Andrei Popescu is 22 years old and likes Linux
Ioana David is 23 years old and likes macOS
```

We investigate the memory leaks of the two programs by using [Valgrind](https://valgrind.org/):

```console
student@os:~/.../memory-leak$ valgrind ./memory_leak
==22362== Memcheck, a memory error detector
==22362== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==22362== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==22362== Command: ./memory_leak
==22362==
Andrei Popescu is 22 years old and likes Linux
Ioana David is 23 years old and likes macOS
==22362==
==22362== HEAP SUMMARY:
==22362==     in use at exit: 72 bytes in 1 blocks
==22362==   total heap usage: 4 allocs, 3 frees, 73,872 bytes allocated
==22362==
==22362== LEAK SUMMARY:
==22362==    definitely lost: 72 bytes in 1 blocks
==22362==    indirectly lost: 0 bytes in 0 blocks
==22362==      possibly lost: 0 bytes in 0 blocks
==22362==    still reachable: 0 bytes in 0 blocks
==22362==         suppressed: 0 bytes in 0 blocks
==22362== Rerun with --leak-check=full to see details of leaked memory
==22362==
==22362== For counts of detected and suppressed errors, rerun with: -v
==22362== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

student@os:~/.../memory-leak$ valgrind ./memory_leak_malloc
==22369== Memcheck, a memory error detector
==22369== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==22369== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==22369== Command: ./memory_leak_malloc
==22369==
Andrei Popescu is 22 years old and likes Linux
Ioana David is 23 years old and likes macOS
==22369==
==22369== HEAP SUMMARY:
==22369==     in use at exit: 148 bytes in 1 blocks
==22369==   total heap usage: 3 allocs, 2 frees, 1,320 bytes allocated
==22369==
==22369== LEAK SUMMARY:
==22369==    definitely lost: 148 bytes in 1 blocks
==22369==    indirectly lost: 0 bytes in 0 blocks
==22369==      possibly lost: 0 bytes in 0 blocks
==22369==    still reachable: 0 bytes in 0 blocks
==22369==         suppressed: 0 bytes in 0 blocks
==22369== Rerun with --leak-check=full to see details of leaked memory
==22369==
==22369== For counts of detected and suppressed errors, rerun with: -v
==22369== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

As we are doing allocations that are not freed, this results in memory leaks.

For `malloc()`-based programs, we can use [`mtrace()` feature](https://man7.org/linux/man-pages/man3/mtrace.3.html) and [`mtrace` command](https://man7.org/linux/man-pages/man1/mtrace.1.html) to verify proper allocations with `malloc()` and deallocations with `free()`.
We call `mtrace()` in the program (in `memory_leak_malloc.c`) to enable `malloc()` and `free()` checking.

To use `mtrace()` we define the `MALLOC_TRACE` environment variable.
We probably also require to preload the libc malloc debugging library, so we use `LD_PRELOAD` for that.
Note that the file path used for `LD_PRELOAD` may need to be updated, depending on your distribution:

```console
student@os:~/.../memory-leak$ LD_PRELOAD=/lib/x86_64-linux-gnu/libc_malloc_debug.so.0 MALLOC_TRACE=mem.trace ./memory_leak_malloc
Andrei Popescu is 22 years old and likes Linux
Ioana David is 23 years old and likes macOS
```

Subsequently, we use the `mtrace` tool to show information about the leaked data:

```console
student@os:~/.../memory-leak$ mtrace ./memory_leak_malloc mem.trace
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/memory-security/drills/tasks/aslr/README.md
> +## Practice
```suggestion
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/memory-security/drills/tasks/aslr/README.md
> +Use the `Makefile.aslr` file to compile the `drills/tasks/aslr/support/aslr.c` file:
```suggestion
Use the `Makefile.aslr` file to compile the `chapters/data/memory-security/drills/tasks/aslr/support/aslr.c` file:
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/memory-security/drills/tasks/bypassing-stack-protector/README.md
> +Inspect the `drills/tasks/bypassing-stack-protector/support/stack_protector.c` source file.
```suggestion
Inspect the `chapters/data/memory-security/drills/tasks/bypassing-stack-protector/support/stack_protector.c` source file.
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/memory-security/drills/tasks/bypassing-stack-protector/support/Makefile
> +
```suggestion
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/memory-security/drills/tasks/exec-shellcode/README.md
> +Navigate to the `drills/tasks/exec-shellcode/support/` directory.
```suggestion
Navigate to the `chapters/data/memory-security/drills/tasks/exec-shellcode/support/` directory.
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/memory-security/drills/tasks/pointer-arithmetic-leak/README.md
> +
```suggestion
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/memory-security/drills/tasks/pointer-arithmetic-leak/README.md
> +
```suggestion
Navigate to the `chapters/data/memory-security/drills/tasks/bypassing-stack-protector/support/` directory. Open and analyze the `buff_leak.c` file.

```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/memory-security/drills/tasks/pointer-arithmetic-leak/support/Makefile
> +
```suggestion
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/memory-security/drills/tasks/stack-protector/README.md
> +## Practice
```suggestion
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/memory-security/drills/tasks/stack-protector/support/Makefile
> +
```suggestion
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/memory-security/drills/tasks/stack-protector/README.md
> +Comment the `-fno-stack-protector` switch from the `drills/tasks/stack-protector/support/Makefile`, recompile and run the `bo_practice_write` executable.
```suggestion
Comment the `-fno-stack-protector` switch from the `chapters/data/memory-security/drills/tasks/stack-protector/support/Makefile`, recompile and run the `bo_practice_write` executable.
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/memory-security/guides/buffer-overflow-leak/README.md
> +Navigate to the `guide/buffer-overflow-leak/` directory.
```suggestion
Navigate to the `chapters/data/memory-security/guides/buffer-overflow-leak/support/` directory.
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/memory-security/guides/buffer-overflow-leak/README.md
> +student@os:~/.../guides/buffer-overflow-leak/$ ./string_leak | xxd
```suggestion
student@os:~/.../guides/buffer-overflow-leak/support/$ ./string_leak | xxd
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/memory-security/guides/buffer-overflow-leak/support/Makefile
> +
```suggestion
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/memory-security/guides/buffer-overflow-overwrite/README.md
> +Take for example the code in `guides/buffer-overflow-overwrite/support/bo_write.c`.
```suggestion
Take for example the code in `chapters/data/memory-security/guides/buffer-overflow-overwrite/support/bo_write.c`.
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/process-memory/drills/questions/page-allocation.md
> +student@os:~/.../drills/tasks/static-dynamic/support$ size hello-static
```suggestion
student@os:~/.../drills/tasks/static-dynamic/support$ size hello-static
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/process-memory/drills/tasks/copy/README.md
> +## Practice
```suggestion
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/process-memory/drills/tasks/copy/README.md
> +
Add the full path to the directory where students are supposed to navigate.

2024-10-07 15:48 UTC, teodutu commented on chapters/data/process-memory/drills/tasks/memory-areas/README.md
> +Enter the `drills/tasks/memory-areas/support` directory.
```suggestion
Enter the `chapters/data/process-memory/drills/tasks/memory-areas/support` directory.
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/process-memory/drills/tasks/modify-areas/README.md
> +## Practice
```suggestion
```
And add the full path to the directory to navigate to (starting from `chapters/...`)

2024-10-07 15:48 UTC, teodutu commented on chapters/data/process-memory/drills/tasks/page-mapper/README.md
> +Navigate to the `drills/tasks/support/page-mapper/` directory.
```suggestion

Navigate to the `chapters/data/process-memory/drills/tasks/support/page-mapper/` directory.
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/process-memory/drills/tasks/reference-counting/README.md
> +Navigate to the `drills/tasks/reference-counting/support` directory.
```suggestion

Navigate to the `chapters/data/process-memory/drills/tasks/reference-counting/support` directory.
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/process-memory/drills/tasks/reference-counting/README.md
> +Navigate to the `drills/tasks/reference-counting/support` directory.
```suggestion
Navigate to the `chapters/data/process-memory/drills/tasks/reference-counting/support` directory.
```

2024-10-07 15:48 UTC, teodutu commented on chapters/data/process-memory/drills/tasks/static-dynamic/README.md
> +## Practice
```suggestion
```

2024-10-07 15:48 UTC, teodutu commented on config.yaml
> +                    - Reading: reading/overview.md
Move this under lab 3. This is just the introduction.

2024-10-07 15:48 UTC, teodutu commented on config.yaml
> +                                - Access Counter/: access-counter/
```suggestion
                                - Bonus - Access Counter/: access-counter/
```

2024-10-07 15:48 UTC, teodutu commented on config.yaml
> +                          - Memory Vuln/: memory-vuln/
```suggestion
                          - Memory Vulnerabilities/: memory-vuln/
```

2024-10-07 15:48 UTC, teodutu commented on config.yaml
> +                                - Reference Counting/: reference-counting/
```suggestion
                                - Bonus - Reference Counting/: reference-counting/
```

2024-10-07 15:48 UTC, teodutu commented on config.yaml
> +                                - Page Mapper/: page-mapper/
```suggestion
                                - Bonus - Page Mapper/: page-mapper/
```

2024-10-07 15:48 UTC, teodutu commented on config.yaml
> +                          - Valgrind leaks: valgrind-leaks.md
```suggestion
                          - Memory Leaks: memory-leaks.md
                          - Valgrind Leaks: valgrind-leaks.md
```

2024-10-13 18:57 UTC, razvand requested changes

2024-10-13 18:57 UTC, razvand commented on chapters/data/investigate-memory/guides/jemalloc/README.md
> +[jemalloc](http://jemalloc.net/) is a featureful allocator that is intended to replace the standard allocator in the standard C library (libc).
```suggestion
[`jemalloc`](http://jemalloc.net/) is a featureful allocator that is intended to replace the standard allocator in the standard C library (libc).
```

2024-10-13 18:57 UTC, razvand commented on chapters/data/investigate-memory/guides/memory-leak/README.md
> +Enter the chapters/data/investigate-memory/guides/memory-leak/support` folder.
```suggestion
Enter the `chapters/data/investigate-memory/guides/memory-leak/support/` directory.
```

2024-10-13 18:57 UTC, razvand commented on chapters/data/investigate-memory/guides/memory-leak/README.md
> +We probably also require to preload the libc malloc debugging library, so we use `LD_PRELOAD` for that.
```suggestion
We probably also require to preload the libc `malloc` debugging library, so we use `LD_PRELOAD` for that.
```

2024-10-13 18:57 UTC, razvand commented on chapters/data/working-with-memory/guides/memory-vuln/README.md
> +At that time the resource constraints - DRAM memory was around a few KBs, operating systems were in their infancy, branch predictors did not exist etc. - were overwhelming.
```suggestion
At that time the resource constraints - DRAM memory was around a few KB, operating systems were in their infancy, branch predictors did not exist etc. - were overwhelming.
```

2024-10-14 20:08 UTC, razvand approved these changes
Thank you all for restructuring this.

2024-10-15 08:40 UTC, merged