Modified basic-syscall and syscall-wrappers infrastructure
cs-pub-ro/operating-systems pull request #78
Opened 2024-09-25 11:07 UTC by SorinAlexB

Added checkers and modified files

# Prerequisite Checklist

- [ ] Read the [contribution guidelines](https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [ ] Tested your changes against relevant architectures and platforms;
- [ ] Updated relevant documentation (if needed).

## Description of changes

2024-09-29 18:05 UTC, teodutu requested changes
Having the tests only in the `solution/` folder doesn't seem to be the way to go. Add a command to the makefiles so that `make skels` also copies the tests to the `support/` folder.

In addition, fix the liter failures.

2024-09-29 18:05 UTC, teodutu commented on chapters/software-stack/system-calls/drills/tasks/syscall-wrapper/solution/tests/checker.sh
> +    echo "main ...................... failed ... 0"
This only tests `read()` and `write()`. To test `itoa()` and `reverse_string()`, change the former's name to `os_itoa()` or something and compare their outputs to `itoa()` and `strrev()`. You can test `getpid()` by changing its name in `syscall.asm` to `os_getpid()` and comparing its output to the real `getpid()`.

2024-09-29 18:05 UTC, teodutu commented on chapters/software-stack/system-calls/drills/tasks/syscall-wrapper/solution/src/main.c
Change the `main()` function to test `itoa()` and `reverse_string()` separately before testing `getpid()` using `itoa()`.

2024-10-06 17:12 UTC, SorinAlexB commented on chapters/software-stack/system-calls/drills/tasks/syscall-wrapper/solution/tests/checker.sh
> +head -n 3 "$out" > /tmp/out.txt
Students should implement the getpid syscall wrapper. I assumed it should not be tested, so the checker evaluates just the first three lines of output(read and write syscalls).

2024-10-06 17:17 UTC, teodutu commented on chapters/software-stack/system-calls/drills/tasks/syscall-wrapper/solution/tests/checker.sh
> +head -n 3 "$out" > /tmp/out.txt
It should be tested. Students need a way to be sure they're using the right syscall number.

2024-10-06 18:28 UTC, teodutu commented
Fuck me. TIL that `strrev()` isn't supported by GCC :upside_down_face: [1]. And you can use `snprintf()` as an implementation for `itoa()` [2].

[1] https://stackoverflow.com/a/58898320
[2] https://stackoverflow.com/a/12970536

2024-10-06 21:03 UTC, teodutu requested changes
Just add the `make` commands to the checkers and update the paths to the binaries. Regarding testing `syscall-wrapper` granularly, let's leave it as it is for now and I'll convert this into an issue for a later time so we can merge this now.

2024-10-06 21:03 UTC, teodutu commented on chapters/software-stack/system-calls/drills/tasks/syscall-wrapper/solution/tests/checker.sh
> +fi
You should make this test more granular: test each functionality individually, not all of them at once.

2024-10-06 21:13 UTC, teodutu approved these changes

2024-10-06 21:16 UTC, merged